# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.models.webhook_with_secret import WebhookWithSecret

class TestWebhookWithSecret(unittest.TestCase):
    """WebhookWithSecret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookWithSecret:
        """Test WebhookWithSecret
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookWithSecret`
        """
        model = WebhookWithSecret()
        if include_optional:
            return WebhookWithSecret(
                id = 'yl9k2m0c8x1',
                url = 'https://sualoja.com.br/webhook',
                active = True,
                events = [
                    'TRANSACTION_PENDING'
                    ],
                has_secret = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                secret = 'whsec_9f8a2b7c6d5e4f3a2b1c0d9e8f7a6b5c'
            )
        else:
            return WebhookWithSecret(
        )
        """

    def testWebhookWithSecret(self):
        """Test WebhookWithSecret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
