# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_delete_user_webhook(self) -> None:
        """Test case for delete_user_webhook

        Delete webhook
        """
        pass

    def test_get_user_webhook(self) -> None:
        """Test case for get_user_webhook

        Get webhook
        """
        pass

    def test_get_user_webhook_sent_detail(self) -> None:
        """Test case for get_user_webhook_sent_detail

        Get sent callback detail
        """
        pass

    def test_get_user_webhooks(self) -> None:
        """Test case for get_user_webhooks

        List webhooks
        """
        pass

    def test_get_user_webhooks_sent_quantity(self) -> None:
        """Test case for get_user_webhooks_sent_quantity

        Count sent callbacks
        """
        pass

    def test_patch_user_webhook(self) -> None:
        """Test case for patch_user_webhook

        Update webhook
        """
        pass

    def test_post_user_webhook(self) -> None:
        """Test case for post_user_webhook

        Create webhook
        """
        pass

    def test_post_user_webhook_rotate_secret(self) -> None:
        """Test case for post_user_webhook_rotate_secret

        Rotate webhook secret
        """
        pass


if __name__ == '__main__':
    unittest.main()
