# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuPlus/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuPlus/payzu-sdks 

    The version of the OpenAPI document: 1.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payzu_pix.models.summary import Summary

class TestSummary(unittest.TestCase):
    """Summary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Summary:
        """Test Summary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Summary`
        """
        model = Summary()
        if include_optional:
            return Summary(
                total_transactions = 56,
                deposit = payzu_pix.models.summary_block.SummaryBlock(
                    total_amount = 1.337, 
                    total_transactions = 56, 
                    statuses = payzu_pix.models.summary_block_statuses.SummaryBlock_statuses(
                        pending = payzu_pix.models.summary_status.SummaryStatus(
                            count = 56, 
                            amount = 1.337, 
                            service_fee_charged = 1.337, ), 
                        completed = payzu_pix.models.summary_status.SummaryStatus(
                            count = 56, 
                            amount = 1.337, 
                            service_fee_charged = 1.337, ), 
                        canceled = , 
                        expired = , 
                        refunded = , ), 
                    grouped = [
                        payzu_pix.models.summary_block_grouped_inner.SummaryBlock_grouped_inner(
                            date = '', 
                            amount = 1.337, )
                        ], ),
                withdraw = payzu_pix.models.summary_block.SummaryBlock(
                    total_amount = 1.337, 
                    total_transactions = 56, 
                    statuses = payzu_pix.models.summary_block_statuses.SummaryBlock_statuses(
                        pending = payzu_pix.models.summary_status.SummaryStatus(
                            count = 56, 
                            amount = 1.337, 
                            service_fee_charged = 1.337, ), 
                        completed = payzu_pix.models.summary_status.SummaryStatus(
                            count = 56, 
                            amount = 1.337, 
                            service_fee_charged = 1.337, ), 
                        canceled = , 
                        expired = , 
                        refunded = , ), 
                    grouped = [
                        payzu_pix.models.summary_block_grouped_inner.SummaryBlock_grouped_inner(
                            date = '', 
                            amount = 1.337, )
                        ], ),
                commission = payzu_pix.models.summary_block.SummaryBlock(
                    total_amount = 1.337, 
                    total_transactions = 56, 
                    statuses = payzu_pix.models.summary_block_statuses.SummaryBlock_statuses(
                        pending = payzu_pix.models.summary_status.SummaryStatus(
                            count = 56, 
                            amount = 1.337, 
                            service_fee_charged = 1.337, ), 
                        completed = payzu_pix.models.summary_status.SummaryStatus(
                            count = 56, 
                            amount = 1.337, 
                            service_fee_charged = 1.337, ), 
                        canceled = , 
                        expired = , 
                        refunded = , ), 
                    grouped = [
                        payzu_pix.models.summary_block_grouped_inner.SummaryBlock_grouped_inner(
                            date = '', 
                            amount = 1.337, )
                        ], )
            )
        else:
            return Summary(
        )
        """

    def testSummary(self):
        """Test Summary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
