<?php
/**
 * InfractionDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PayZu\Pix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayZu Pix API
 *
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v2`  Repo: https://github.com/PayZuAI/payzu-sdks
 *
 * The version of the OpenAPI document: 1.8.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayZu\Pix\Model;

use \ArrayAccess;
use \PayZu\Pix\ObjectSerializer;

/**
 * InfractionDetail Class Doc Comment
 *
 * @category Class
 * @package  PayZu\Pix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InfractionDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'InfractionDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'protocol' => 'string',
        'status' => 'string',
        'type' => 'string',
        'reported_by' => 'string',
        'report_details' => 'string',
        'analysis_result' => 'string',
        'analysis_details' => 'string',
        'reported_at' => '\DateTime',
        'expires_at' => '\DateTime',
        'transaction' => '\PayZu\Pix\Model\InfractionDetailTransaction',
        'defense_history' => '\PayZu\Pix\Model\DefenseHistoryEntry[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'protocol' => null,
        'status' => null,
        'type' => null,
        'reported_by' => null,
        'report_details' => null,
        'analysis_result' => null,
        'analysis_details' => null,
        'reported_at' => 'date-time',
        'expires_at' => 'date-time',
        'transaction' => null,
        'defense_history' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'protocol' => false,
        'status' => false,
        'type' => false,
        'reported_by' => false,
        'report_details' => true,
        'analysis_result' => true,
        'analysis_details' => true,
        'reported_at' => false,
        'expires_at' => true,
        'transaction' => false,
        'defense_history' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'protocol' => 'protocol',
        'status' => 'status',
        'type' => 'type',
        'reported_by' => 'reportedBy',
        'report_details' => 'reportDetails',
        'analysis_result' => 'analysisResult',
        'analysis_details' => 'analysisDetails',
        'reported_at' => 'reportedAt',
        'expires_at' => 'expiresAt',
        'transaction' => 'transaction',
        'defense_history' => 'defenseHistory'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'protocol' => 'setProtocol',
        'status' => 'setStatus',
        'type' => 'setType',
        'reported_by' => 'setReportedBy',
        'report_details' => 'setReportDetails',
        'analysis_result' => 'setAnalysisResult',
        'analysis_details' => 'setAnalysisDetails',
        'reported_at' => 'setReportedAt',
        'expires_at' => 'setExpiresAt',
        'transaction' => 'setTransaction',
        'defense_history' => 'setDefenseHistory'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'protocol' => 'getProtocol',
        'status' => 'getStatus',
        'type' => 'getType',
        'reported_by' => 'getReportedBy',
        'report_details' => 'getReportDetails',
        'analysis_result' => 'getAnalysisResult',
        'analysis_details' => 'getAnalysisDetails',
        'reported_at' => 'getReportedAt',
        'expires_at' => 'getExpiresAt',
        'transaction' => 'getTransaction',
        'defense_history' => 'getDefenseHistory'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_WAITING_PSP = 'WAITING_PSP';
    public const STATUS_CLOSED = 'CLOSED';
    public const STATUS_OPEN = 'OPEN';
    public const STATUS_CANCELLED = 'CANCELLED';
    public const STATUS_ACKNOWLEDGED = 'ACKNOWLEDGED';
    public const STATUS_DEFENDED = 'DEFENDED';
    public const STATUS_ANSWERED = 'ANSWERED';
    public const STATUS_WAITING_ADJUSTMENTS = 'WAITING_ADJUSTMENTS';
    public const TYPE_REFUND_REQUEST = 'REFUND_REQUEST';
    public const TYPE_FRAUD = 'FRAUD';
    public const TYPE_REFUND_CANCELLED = 'REFUND_CANCELLED';
    public const REPORTED_BY_DEBITED_PARTICIPANT = 'DEBITED_PARTICIPANT';
    public const REPORTED_BY_CREDITED_PARTICIPANT = 'CREDITED_PARTICIPANT';
    public const ANALYSIS_RESULT_AGREED = 'AGREED';
    public const ANALYSIS_RESULT_DISAGREED = 'DISAGREED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_WAITING_PSP,
            self::STATUS_CLOSED,
            self::STATUS_OPEN,
            self::STATUS_CANCELLED,
            self::STATUS_ACKNOWLEDGED,
            self::STATUS_DEFENDED,
            self::STATUS_ANSWERED,
            self::STATUS_WAITING_ADJUSTMENTS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_REFUND_REQUEST,
            self::TYPE_FRAUD,
            self::TYPE_REFUND_CANCELLED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReportedByAllowableValues()
    {
        return [
            self::REPORTED_BY_DEBITED_PARTICIPANT,
            self::REPORTED_BY_CREDITED_PARTICIPANT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAnalysisResultAllowableValues()
    {
        return [
            self::ANALYSIS_RESULT_AGREED,
            self::ANALYSIS_RESULT_DISAGREED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('protocol', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('reported_by', $data ?? [], null);
        $this->setIfExists('report_details', $data ?? [], null);
        $this->setIfExists('analysis_result', $data ?? [], null);
        $this->setIfExists('analysis_details', $data ?? [], null);
        $this->setIfExists('reported_at', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('transaction', $data ?? [], null);
        $this->setIfExists('defense_history', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getReportedByAllowableValues();
        if (!is_null($this->container['reported_by']) && !in_array($this->container['reported_by'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reported_by', must be one of '%s'",
                $this->container['reported_by'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAnalysisResultAllowableValues();
        if (!is_null($this->container['analysis_result']) && !in_array($this->container['analysis_result'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'analysis_result', must be one of '%s'",
                $this->container['analysis_result'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Identifier of the infraction inside PayZu, used in the query routes and when sending the defense.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets protocol
     *
     * @return string|null
     */
    public function getProtocol()
    {
        return $this->container['protocol'];
    }

    /**
     * Sets protocol
     *
     * @param string|null $protocol Infraction code at Bacen.
     *
     * @return self
     */
    public function setProtocol($protocol)
    {
        if (is_null($protocol)) {
            throw new \InvalidArgumentException('non-nullable protocol cannot be null');
        }
        $this->container['protocol'] = $protocol;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Current state of the infraction.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type Type of the infraction: REFUND_REQUEST, FRAUD or REFUND_CANCELLED.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets reported_by
     *
     * @return string|null
     */
    public function getReportedBy()
    {
        return $this->container['reported_by'];
    }

    /**
     * Sets reported_by
     *
     * @param string|null $reported_by Side that opened the infraction: DEBITED_PARTICIPANT or CREDITED_PARTICIPANT.
     *
     * @return self
     */
    public function setReportedBy($reported_by)
    {
        if (is_null($reported_by)) {
            throw new \InvalidArgumentException('non-nullable reported_by cannot be null');
        }
        $this->container['reported_by'] = $reported_by;

        return $this;
    }

    /**
     * Gets report_details
     *
     * @return string|null
     */
    public function getReportDetails()
    {
        return $this->container['report_details'];
    }

    /**
     * Sets report_details
     *
     * @param string|null $report_details Reason given by whoever opened the infraction, in the text sent by the partner bank.
     *
     * @return self
     */
    public function setReportDetails($report_details)
    {
        if (is_null($report_details)) {
            array_push($this->openAPINullablesSetToNull, 'report_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('report_details', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['report_details'] = $report_details;

        return $this;
    }

    /**
     * Gets analysis_result
     *
     * @return string|null
     */
    public function getAnalysisResult()
    {
        return $this->container['analysis_result'];
    }

    /**
     * Sets analysis_result
     *
     * @param string|null $analysis_result Analysis outcome: AGREED or DISAGREED.
     *
     * @return self
     */
    public function setAnalysisResult($analysis_result)
    {
        if (is_null($analysis_result)) {
            array_push($this->openAPINullablesSetToNull, 'analysis_result');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('analysis_result', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['analysis_result'] = $analysis_result;

        return $this;
    }

    /**
     * Gets analysis_details
     *
     * @return string|null
     */
    public function getAnalysisDetails()
    {
        return $this->container['analysis_details'];
    }

    /**
     * Sets analysis_details
     *
     * @param string|null $analysis_details Additional text about the analysis decision, when the partner bank sends that information.
     *
     * @return self
     */
    public function setAnalysisDetails($analysis_details)
    {
        if (is_null($analysis_details)) {
            array_push($this->openAPINullablesSetToNull, 'analysis_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('analysis_details', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['analysis_details'] = $analysis_details;

        return $this;
    }

    /**
     * Gets reported_at
     *
     * @return \DateTime|null
     */
    public function getReportedAt()
    {
        return $this->container['reported_at'];
    }

    /**
     * Sets reported_at
     *
     * @param \DateTime|null $reported_at Moment the infraction was opened.
     *
     * @return self
     */
    public function setReportedAt($reported_at)
    {
        if (is_null($reported_at)) {
            throw new \InvalidArgumentException('non-nullable reported_at cannot be null');
        }
        $this->container['reported_at'] = $reported_at;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at Deadline to send the defense of this infraction.
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            array_push($this->openAPINullablesSetToNull, 'expires_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets transaction
     *
     * @return \PayZu\Pix\Model\InfractionDetailTransaction|null
     */
    public function getTransaction()
    {
        return $this->container['transaction'];
    }

    /**
     * Sets transaction
     *
     * @param \PayZu\Pix\Model\InfractionDetailTransaction|null $transaction transaction
     *
     * @return self
     */
    public function setTransaction($transaction)
    {
        if (is_null($transaction)) {
            throw new \InvalidArgumentException('non-nullable transaction cannot be null');
        }
        $this->container['transaction'] = $transaction;

        return $this;
    }

    /**
     * Gets defense_history
     *
     * @return \PayZu\Pix\Model\DefenseHistoryEntry[]|null
     */
    public function getDefenseHistory()
    {
        return $this->container['defense_history'];
    }

    /**
     * Sets defense_history
     *
     * @param \PayZu\Pix\Model\DefenseHistoryEntry[]|null $defense_history Defenses already sent for this infraction, each with text, status and files.
     *
     * @return self
     */
    public function setDefenseHistory($defense_history)
    {
        if (is_null($defense_history)) {
            throw new \InvalidArgumentException('non-nullable defense_history cannot be null');
        }
        $this->container['defense_history'] = $defense_history;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


