/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v2`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package br.com.payzu.pix.api;

import br.com.payzu.pix.ApiClient;
import br.com.payzu.pix.ApiException;
import br.com.payzu.pix.ApiResponse;
import br.com.payzu.pix.Configuration;
import br.com.payzu.pix.Pair;

import br.com.payzu.pix.model.ApiError;
import java.math.BigDecimal;
import br.com.payzu.pix.model.Defense;
import java.io.File;
import br.com.payzu.pix.model.InfractionDetail;
import br.com.payzu.pix.model.InfractionListResponse;
import java.time.OffsetDateTime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class InfractionsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public InfractionsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public InfractionsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * List Infractions
   * List all infractions for the authenticated user with pagination and filters.
   * @param page Page number. (optional, default to 1)
   * @param limit Items per page. (optional, default to 10)
   * @param status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
   * @param type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
   * @param endToEndId End-to-end ID of the Pix. (optional)
   * @param transactionId Transaction ID. (optional)
   * @param amountMin Minimum amount. (optional)
   * @param amountMax Maximum amount. (optional)
   * @param analysisResult Comma-separated AnalysisResult: AGREED, DISAGREED. (optional)
   * @param reportedBy Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
   * @param participantDocument CPF or CNPJ of the participant. (optional)
   * @param participantName Name of the participant. (optional)
   * @param sortBy Sort field. (optional, default to createdAt)
   * @param sortDirection Sort direction. (optional, default to desc)
   * @param reportedAtFrom Filter: reportedAt from. (optional)
   * @param reportedAtTo Filter: reportedAt up to. (optional)
   * @param createdAtFrom Filter: createdAt from. (optional)
   * @param createdAtTo Filter: createdAt up to. (optional)
   * @param expiresAtFrom Filter: expiresAt from. (optional)
   * @param expiresAtTo Filter: expiresAt up to. (optional)
   * @param updatedAtFrom Filter: updatedAt from. (optional)
   * @param updatedAtTo Filter: updatedAt up to. (optional)
   * @param id Filter by infraction ID. (optional)
   * @param protocol Filter by protocol. (optional)
   * @return InfractionListResponse
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Infractions Documentation</a>
   */
  public InfractionListResponse getInfractions(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String status, @javax.annotation.Nullable String type, @javax.annotation.Nullable String endToEndId, @javax.annotation.Nullable String transactionId, @javax.annotation.Nullable BigDecimal amountMin, @javax.annotation.Nullable BigDecimal amountMax, @javax.annotation.Nullable String analysisResult, @javax.annotation.Nullable String reportedBy, @javax.annotation.Nullable String participantDocument, @javax.annotation.Nullable String participantName, @javax.annotation.Nullable String sortBy, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable OffsetDateTime reportedAtFrom, @javax.annotation.Nullable OffsetDateTime reportedAtTo, @javax.annotation.Nullable OffsetDateTime createdAtFrom, @javax.annotation.Nullable OffsetDateTime createdAtTo, @javax.annotation.Nullable OffsetDateTime expiresAtFrom, @javax.annotation.Nullable OffsetDateTime expiresAtTo, @javax.annotation.Nullable OffsetDateTime updatedAtFrom, @javax.annotation.Nullable OffsetDateTime updatedAtTo, @javax.annotation.Nullable String id, @javax.annotation.Nullable String protocol) throws ApiException {
    return getInfractions(page, limit, status, type, endToEndId, transactionId, amountMin, amountMax, analysisResult, reportedBy, participantDocument, participantName, sortBy, sortDirection, reportedAtFrom, reportedAtTo, createdAtFrom, createdAtTo, expiresAtFrom, expiresAtTo, updatedAtFrom, updatedAtTo, id, protocol, null);
  }

  /**
   * List Infractions
   * List all infractions for the authenticated user with pagination and filters.
   * @param page Page number. (optional, default to 1)
   * @param limit Items per page. (optional, default to 10)
   * @param status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
   * @param type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
   * @param endToEndId End-to-end ID of the Pix. (optional)
   * @param transactionId Transaction ID. (optional)
   * @param amountMin Minimum amount. (optional)
   * @param amountMax Maximum amount. (optional)
   * @param analysisResult Comma-separated AnalysisResult: AGREED, DISAGREED. (optional)
   * @param reportedBy Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
   * @param participantDocument CPF or CNPJ of the participant. (optional)
   * @param participantName Name of the participant. (optional)
   * @param sortBy Sort field. (optional, default to createdAt)
   * @param sortDirection Sort direction. (optional, default to desc)
   * @param reportedAtFrom Filter: reportedAt from. (optional)
   * @param reportedAtTo Filter: reportedAt up to. (optional)
   * @param createdAtFrom Filter: createdAt from. (optional)
   * @param createdAtTo Filter: createdAt up to. (optional)
   * @param expiresAtFrom Filter: expiresAt from. (optional)
   * @param expiresAtTo Filter: expiresAt up to. (optional)
   * @param updatedAtFrom Filter: updatedAt from. (optional)
   * @param updatedAtTo Filter: updatedAt up to. (optional)
   * @param id Filter by infraction ID. (optional)
   * @param protocol Filter by protocol. (optional)
   * @param headers Optional headers to include in the request
   * @return InfractionListResponse
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Infractions Documentation</a>
   */
  public InfractionListResponse getInfractions(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String status, @javax.annotation.Nullable String type, @javax.annotation.Nullable String endToEndId, @javax.annotation.Nullable String transactionId, @javax.annotation.Nullable BigDecimal amountMin, @javax.annotation.Nullable BigDecimal amountMax, @javax.annotation.Nullable String analysisResult, @javax.annotation.Nullable String reportedBy, @javax.annotation.Nullable String participantDocument, @javax.annotation.Nullable String participantName, @javax.annotation.Nullable String sortBy, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable OffsetDateTime reportedAtFrom, @javax.annotation.Nullable OffsetDateTime reportedAtTo, @javax.annotation.Nullable OffsetDateTime createdAtFrom, @javax.annotation.Nullable OffsetDateTime createdAtTo, @javax.annotation.Nullable OffsetDateTime expiresAtFrom, @javax.annotation.Nullable OffsetDateTime expiresAtTo, @javax.annotation.Nullable OffsetDateTime updatedAtFrom, @javax.annotation.Nullable OffsetDateTime updatedAtTo, @javax.annotation.Nullable String id, @javax.annotation.Nullable String protocol, Map<String, String> headers) throws ApiException {
    ApiResponse<InfractionListResponse> localVarResponse = getInfractionsWithHttpInfo(page, limit, status, type, endToEndId, transactionId, amountMin, amountMax, analysisResult, reportedBy, participantDocument, participantName, sortBy, sortDirection, reportedAtFrom, reportedAtTo, createdAtFrom, createdAtTo, expiresAtFrom, expiresAtTo, updatedAtFrom, updatedAtTo, id, protocol, headers);
    return localVarResponse.getData();
  }

  /**
   * List Infractions
   * List all infractions for the authenticated user with pagination and filters.
   * @param page Page number. (optional, default to 1)
   * @param limit Items per page. (optional, default to 10)
   * @param status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
   * @param type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
   * @param endToEndId End-to-end ID of the Pix. (optional)
   * @param transactionId Transaction ID. (optional)
   * @param amountMin Minimum amount. (optional)
   * @param amountMax Maximum amount. (optional)
   * @param analysisResult Comma-separated AnalysisResult: AGREED, DISAGREED. (optional)
   * @param reportedBy Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
   * @param participantDocument CPF or CNPJ of the participant. (optional)
   * @param participantName Name of the participant. (optional)
   * @param sortBy Sort field. (optional, default to createdAt)
   * @param sortDirection Sort direction. (optional, default to desc)
   * @param reportedAtFrom Filter: reportedAt from. (optional)
   * @param reportedAtTo Filter: reportedAt up to. (optional)
   * @param createdAtFrom Filter: createdAt from. (optional)
   * @param createdAtTo Filter: createdAt up to. (optional)
   * @param expiresAtFrom Filter: expiresAt from. (optional)
   * @param expiresAtTo Filter: expiresAt up to. (optional)
   * @param updatedAtFrom Filter: updatedAt from. (optional)
   * @param updatedAtTo Filter: updatedAt up to. (optional)
   * @param id Filter by infraction ID. (optional)
   * @param protocol Filter by protocol. (optional)
   * @return ApiResponse&lt;InfractionListResponse&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Infractions Documentation</a>
   */
  public ApiResponse<InfractionListResponse> getInfractionsWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String status, @javax.annotation.Nullable String type, @javax.annotation.Nullable String endToEndId, @javax.annotation.Nullable String transactionId, @javax.annotation.Nullable BigDecimal amountMin, @javax.annotation.Nullable BigDecimal amountMax, @javax.annotation.Nullable String analysisResult, @javax.annotation.Nullable String reportedBy, @javax.annotation.Nullable String participantDocument, @javax.annotation.Nullable String participantName, @javax.annotation.Nullable String sortBy, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable OffsetDateTime reportedAtFrom, @javax.annotation.Nullable OffsetDateTime reportedAtTo, @javax.annotation.Nullable OffsetDateTime createdAtFrom, @javax.annotation.Nullable OffsetDateTime createdAtTo, @javax.annotation.Nullable OffsetDateTime expiresAtFrom, @javax.annotation.Nullable OffsetDateTime expiresAtTo, @javax.annotation.Nullable OffsetDateTime updatedAtFrom, @javax.annotation.Nullable OffsetDateTime updatedAtTo, @javax.annotation.Nullable String id, @javax.annotation.Nullable String protocol) throws ApiException {
    return getInfractionsWithHttpInfo(page, limit, status, type, endToEndId, transactionId, amountMin, amountMax, analysisResult, reportedBy, participantDocument, participantName, sortBy, sortDirection, reportedAtFrom, reportedAtTo, createdAtFrom, createdAtTo, expiresAtFrom, expiresAtTo, updatedAtFrom, updatedAtTo, id, protocol, null);
  }

  /**
   * List Infractions
   * List all infractions for the authenticated user with pagination and filters.
   * @param page Page number. (optional, default to 1)
   * @param limit Items per page. (optional, default to 10)
   * @param status Comma-separated InfractionStatus (WAITING_PSP,CLOSED,OPEN,CANCELLED,ACKNOWLEDGED,DEFENDED,ANSWERED,WAITING_ADJUSTMENTS) (optional)
   * @param type Comma-separated InfractionType (REFUND_REQUEST,FRAUD,REFUND_CANCELLED) (optional)
   * @param endToEndId End-to-end ID of the Pix. (optional)
   * @param transactionId Transaction ID. (optional)
   * @param amountMin Minimum amount. (optional)
   * @param amountMax Maximum amount. (optional)
   * @param analysisResult Comma-separated AnalysisResult: AGREED, DISAGREED. (optional)
   * @param reportedBy Comma-separated ReportedType (DEBITED_PARTICIPANT,CREDITED_PARTICIPANT) (optional)
   * @param participantDocument CPF or CNPJ of the participant. (optional)
   * @param participantName Name of the participant. (optional)
   * @param sortBy Sort field. (optional, default to createdAt)
   * @param sortDirection Sort direction. (optional, default to desc)
   * @param reportedAtFrom Filter: reportedAt from. (optional)
   * @param reportedAtTo Filter: reportedAt up to. (optional)
   * @param createdAtFrom Filter: createdAt from. (optional)
   * @param createdAtTo Filter: createdAt up to. (optional)
   * @param expiresAtFrom Filter: expiresAt from. (optional)
   * @param expiresAtTo Filter: expiresAt up to. (optional)
   * @param updatedAtFrom Filter: updatedAt from. (optional)
   * @param updatedAtTo Filter: updatedAt up to. (optional)
   * @param id Filter by infraction ID. (optional)
   * @param protocol Filter by protocol. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;InfractionListResponse&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Infractions Documentation</a>
   */
  public ApiResponse<InfractionListResponse> getInfractionsWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String status, @javax.annotation.Nullable String type, @javax.annotation.Nullable String endToEndId, @javax.annotation.Nullable String transactionId, @javax.annotation.Nullable BigDecimal amountMin, @javax.annotation.Nullable BigDecimal amountMax, @javax.annotation.Nullable String analysisResult, @javax.annotation.Nullable String reportedBy, @javax.annotation.Nullable String participantDocument, @javax.annotation.Nullable String participantName, @javax.annotation.Nullable String sortBy, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable OffsetDateTime reportedAtFrom, @javax.annotation.Nullable OffsetDateTime reportedAtTo, @javax.annotation.Nullable OffsetDateTime createdAtFrom, @javax.annotation.Nullable OffsetDateTime createdAtTo, @javax.annotation.Nullable OffsetDateTime expiresAtFrom, @javax.annotation.Nullable OffsetDateTime expiresAtTo, @javax.annotation.Nullable OffsetDateTime updatedAtFrom, @javax.annotation.Nullable OffsetDateTime updatedAtTo, @javax.annotation.Nullable String id, @javax.annotation.Nullable String protocol, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getInfractionsRequestBuilder(page, limit, status, type, endToEndId, transactionId, amountMin, amountMax, analysisResult, reportedBy, participantDocument, participantName, sortBy, sortDirection, reportedAtFrom, reportedAtTo, createdAtFrom, createdAtTo, expiresAtFrom, expiresAtTo, updatedAtFrom, updatedAtTo, id, protocol, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getInfractions", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<InfractionListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        InfractionListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<InfractionListResponse>() {});
        

        return new ApiResponse<InfractionListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getInfractionsRequestBuilder(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String status, @javax.annotation.Nullable String type, @javax.annotation.Nullable String endToEndId, @javax.annotation.Nullable String transactionId, @javax.annotation.Nullable BigDecimal amountMin, @javax.annotation.Nullable BigDecimal amountMax, @javax.annotation.Nullable String analysisResult, @javax.annotation.Nullable String reportedBy, @javax.annotation.Nullable String participantDocument, @javax.annotation.Nullable String participantName, @javax.annotation.Nullable String sortBy, @javax.annotation.Nullable String sortDirection, @javax.annotation.Nullable OffsetDateTime reportedAtFrom, @javax.annotation.Nullable OffsetDateTime reportedAtTo, @javax.annotation.Nullable OffsetDateTime createdAtFrom, @javax.annotation.Nullable OffsetDateTime createdAtTo, @javax.annotation.Nullable OffsetDateTime expiresAtFrom, @javax.annotation.Nullable OffsetDateTime expiresAtTo, @javax.annotation.Nullable OffsetDateTime updatedAtFrom, @javax.annotation.Nullable OffsetDateTime updatedAtTo, @javax.annotation.Nullable String id, @javax.annotation.Nullable String protocol, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/user/infractions";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));
    localVarQueryParameterBaseName = "type";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("type", type));
    localVarQueryParameterBaseName = "endToEndId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("endToEndId", endToEndId));
    localVarQueryParameterBaseName = "transactionId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("transactionId", transactionId));
    localVarQueryParameterBaseName = "amountMin";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("amountMin", amountMin));
    localVarQueryParameterBaseName = "amountMax";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("amountMax", amountMax));
    localVarQueryParameterBaseName = "analysisResult";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("analysisResult", analysisResult));
    localVarQueryParameterBaseName = "reportedBy";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("reportedBy", reportedBy));
    localVarQueryParameterBaseName = "participantDocument";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("participantDocument", participantDocument));
    localVarQueryParameterBaseName = "participantName";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("participantName", participantName));
    localVarQueryParameterBaseName = "sortBy";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sortBy", sortBy));
    localVarQueryParameterBaseName = "sortDirection";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sortDirection", sortDirection));
    localVarQueryParameterBaseName = "reportedAtFrom";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("reportedAtFrom", reportedAtFrom));
    localVarQueryParameterBaseName = "reportedAtTo";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("reportedAtTo", reportedAtTo));
    localVarQueryParameterBaseName = "createdAtFrom";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("createdAtFrom", createdAtFrom));
    localVarQueryParameterBaseName = "createdAtTo";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("createdAtTo", createdAtTo));
    localVarQueryParameterBaseName = "expiresAtFrom";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("expiresAtFrom", expiresAtFrom));
    localVarQueryParameterBaseName = "expiresAtTo";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("expiresAtTo", expiresAtTo));
    localVarQueryParameterBaseName = "updatedAtFrom";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("updatedAtFrom", updatedAtFrom));
    localVarQueryParameterBaseName = "updatedAtTo";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("updatedAtTo", updatedAtTo));
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));
    localVarQueryParameterBaseName = "protocol";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("protocol", protocol));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Infraction
   * Get a specific infraction by ID.
   * @param id Infraction ID (required)
   * @return InfractionDetail
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Infraction Documentation</a>
   */
  public InfractionDetail getInfractionsById(@javax.annotation.Nonnull String id) throws ApiException {
    return getInfractionsById(id, null);
  }

  /**
   * Get Infraction
   * Get a specific infraction by ID.
   * @param id Infraction ID (required)
   * @param headers Optional headers to include in the request
   * @return InfractionDetail
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Infraction Documentation</a>
   */
  public InfractionDetail getInfractionsById(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<InfractionDetail> localVarResponse = getInfractionsByIdWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get Infraction
   * Get a specific infraction by ID.
   * @param id Infraction ID (required)
   * @return ApiResponse&lt;InfractionDetail&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Infraction Documentation</a>
   */
  public ApiResponse<InfractionDetail> getInfractionsByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getInfractionsByIdWithHttpInfo(id, null);
  }

  /**
   * Get Infraction
   * Get a specific infraction by ID.
   * @param id Infraction ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;InfractionDetail&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Infraction Documentation</a>
   */
  public ApiResponse<InfractionDetail> getInfractionsByIdWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getInfractionsByIdRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getInfractionsById", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<InfractionDetail>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        InfractionDetail responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<InfractionDetail>() {});
        

        return new ApiResponse<InfractionDetail>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getInfractionsByIdRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getInfractionsById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/user/infractions/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get Defense
   * Get a specific defense for an infraction.
   * @param infractionId Infraction ID (required)
   * @param defenseId Defense ID (required)
   * @return Defense
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Defense Documentation</a>
   */
  public Defense getInfractionsDefenseById(@javax.annotation.Nonnull String infractionId, @javax.annotation.Nonnull String defenseId) throws ApiException {
    return getInfractionsDefenseById(infractionId, defenseId, null);
  }

  /**
   * Get Defense
   * Get a specific defense for an infraction.
   * @param infractionId Infraction ID (required)
   * @param defenseId Defense ID (required)
   * @param headers Optional headers to include in the request
   * @return Defense
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Defense Documentation</a>
   */
  public Defense getInfractionsDefenseById(@javax.annotation.Nonnull String infractionId, @javax.annotation.Nonnull String defenseId, Map<String, String> headers) throws ApiException {
    ApiResponse<Defense> localVarResponse = getInfractionsDefenseByIdWithHttpInfo(infractionId, defenseId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get Defense
   * Get a specific defense for an infraction.
   * @param infractionId Infraction ID (required)
   * @param defenseId Defense ID (required)
   * @return ApiResponse&lt;Defense&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Defense Documentation</a>
   */
  public ApiResponse<Defense> getInfractionsDefenseByIdWithHttpInfo(@javax.annotation.Nonnull String infractionId, @javax.annotation.Nonnull String defenseId) throws ApiException {
    return getInfractionsDefenseByIdWithHttpInfo(infractionId, defenseId, null);
  }

  /**
   * Get Defense
   * Get a specific defense for an infraction.
   * @param infractionId Infraction ID (required)
   * @param defenseId Defense ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Defense&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Get Defense Documentation</a>
   */
  public ApiResponse<Defense> getInfractionsDefenseByIdWithHttpInfo(@javax.annotation.Nonnull String infractionId, @javax.annotation.Nonnull String defenseId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getInfractionsDefenseByIdRequestBuilder(infractionId, defenseId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getInfractionsDefenseById", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Defense>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Defense responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Defense>() {});
        

        return new ApiResponse<Defense>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getInfractionsDefenseByIdRequestBuilder(@javax.annotation.Nonnull String infractionId, @javax.annotation.Nonnull String defenseId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'infractionId' is set
    if (infractionId == null) {
      throw new ApiException(400, "Missing the required parameter 'infractionId' when calling getInfractionsDefenseById");
    }
    // verify the required parameter 'defenseId' is set
    if (defenseId == null) {
      throw new ApiException(400, "Missing the required parameter 'defenseId' when calling getInfractionsDefenseById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/user/infractions/{infractionId}/defenses/{defenseId}"
        .replace("{infractionId}", ApiClient.urlEncode(infractionId.toString()))
        .replace("{defenseId}", ApiClient.urlEncode(defenseId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List Defenses
   * List all defenses for a specific infraction.
   * @param id Infraction ID (required)
   * @return List&lt;Defense&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Defenses Documentation</a>
   */
  public List<Defense> getInfractionsDefenses(@javax.annotation.Nonnull String id) throws ApiException {
    return getInfractionsDefenses(id, null);
  }

  /**
   * List Defenses
   * List all defenses for a specific infraction.
   * @param id Infraction ID (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;Defense&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Defenses Documentation</a>
   */
  public List<Defense> getInfractionsDefenses(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<List<Defense>> localVarResponse = getInfractionsDefensesWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * List Defenses
   * List all defenses for a specific infraction.
   * @param id Infraction ID (required)
   * @return ApiResponse&lt;List&lt;Defense&gt;&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Defenses Documentation</a>
   */
  public ApiResponse<List<Defense>> getInfractionsDefensesWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getInfractionsDefensesWithHttpInfo(id, null);
  }

  /**
   * List Defenses
   * List all defenses for a specific infraction.
   * @param id Infraction ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;Defense&gt;&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">List Defenses Documentation</a>
   */
  public ApiResponse<List<Defense>> getInfractionsDefensesWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getInfractionsDefensesRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getInfractionsDefenses", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<Defense>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<Defense> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Defense>>() {});
        

        return new ApiResponse<List<Defense>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getInfractionsDefensesRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getInfractionsDefenses");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/user/infractions/{id}/defenses"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create Defense
   * Create a defense for a specific infraction.
   * @param id Infraction ID (required)
   * @param defense Defense text (max: 1000 characters) (required)
   * @param files Evidence files: up to 5 files, 10 MB each and 10 MB in total. Files .exe, .msi, .bat, .sh and .cmd are rejected. (optional)
   * @return Defense
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Create Defense Documentation</a>
   */
  public Defense postInfractionsDefense(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String defense, @javax.annotation.Nullable List<File> files) throws ApiException {
    return postInfractionsDefense(id, defense, files, null);
  }

  /**
   * Create Defense
   * Create a defense for a specific infraction.
   * @param id Infraction ID (required)
   * @param defense Defense text (max: 1000 characters) (required)
   * @param files Evidence files: up to 5 files, 10 MB each and 10 MB in total. Files .exe, .msi, .bat, .sh and .cmd are rejected. (optional)
   * @param headers Optional headers to include in the request
   * @return Defense
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Create Defense Documentation</a>
   */
  public Defense postInfractionsDefense(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String defense, @javax.annotation.Nullable List<File> files, Map<String, String> headers) throws ApiException {
    ApiResponse<Defense> localVarResponse = postInfractionsDefenseWithHttpInfo(id, defense, files, headers);
    return localVarResponse.getData();
  }

  /**
   * Create Defense
   * Create a defense for a specific infraction.
   * @param id Infraction ID (required)
   * @param defense Defense text (max: 1000 characters) (required)
   * @param files Evidence files: up to 5 files, 10 MB each and 10 MB in total. Files .exe, .msi, .bat, .sh and .cmd are rejected. (optional)
   * @return ApiResponse&lt;Defense&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Create Defense Documentation</a>
   */
  public ApiResponse<Defense> postInfractionsDefenseWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String defense, @javax.annotation.Nullable List<File> files) throws ApiException {
    return postInfractionsDefenseWithHttpInfo(id, defense, files, null);
  }

  /**
   * Create Defense
   * Create a defense for a specific infraction.
   * @param id Infraction ID (required)
   * @param defense Defense text (max: 1000 characters) (required)
   * @param files Evidence files: up to 5 files, 10 MB each and 10 MB in total. Files .exe, .msi, .bat, .sh and .cmd are rejected. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Defense&gt;
   * @throws ApiException if fails to make API call
   * Infractions (MED)
   * @see <a href="/docs/pix-processamento/tutoriais/infractions">Create Defense Documentation</a>
   */
  public ApiResponse<Defense> postInfractionsDefenseWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String defense, @javax.annotation.Nullable List<File> files, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = postInfractionsDefenseRequestBuilder(id, defense, files, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("postInfractionsDefense", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<Defense>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        Defense responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Defense>() {});
        

        return new ApiResponse<Defense>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder postInfractionsDefenseRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String defense, @javax.annotation.Nullable List<File> files, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling postInfractionsDefense");
    }
    // verify the required parameter 'defense' is set
    if (defense == null) {
      throw new ApiException(400, "Missing the required parameter 'defense' when calling postInfractionsDefense");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/user/infractions/{id}/defenses"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    if (defense != null) {
        multiPartBuilder.addTextBody("defense", defense.toString());
    }
    for (int i=0; i < files.size(); i++) {
        multiPartBuilder.addBinaryBody("files", files.get(i));
        hasFiles = true;
    }
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
