=begin
#PayZu Pix API

#REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v3`  Repo: https://github.com/PayZuAI/payzu-sdks 

The version of the OpenAPI document: 1.8.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module PayZuPix
  class DepositPending < ApiModelBase
    # Identifier of the pending deposit.
    attr_accessor :id

    # Deposit status: PENDING, COMPLETED or REJECTED.
    attr_accessor :status

    # Amount received.
    attr_accessor :amount

    # CNPJ of the payer of the Pix.
    attr_accessor :payer_document

    # Name of the payer of the Pix.
    attr_accessor :payer_name

    # Account number of the payer inside the platform.
    attr_accessor :payer_account_number

    # ISPB code of the institution the Pix was sent from.
    attr_accessor :payer_institution_ispb

    # Name of the institution the Pix was sent from.
    attr_accessor :payer_institution_name

    # CPF or CNPJ of the account that received the Pix.
    attr_accessor :receiver_document

    # Name of the account that received the Pix.
    attr_accessor :receiver_name

    # Number of your PayZu account that receives the credit if the deposit is approved.
    attr_accessor :receiver_account_number

    # ISPB code of the institution that received the Pix.
    attr_accessor :receiver_institution_ispb

    # Name of the institution where the Pix was settled on the receiving side.
    attr_accessor :receiver_institution_name

    # End-to-end identifier of the Pix.
    attr_accessor :end_to_end_id

    # Date and time the Pix was settled.
    attr_accessor :paid_at

    attr_accessor :pix_key

    # Free text that would accompany the Pix.
    attr_accessor :description

    # Date and time the deposit was approved.
    attr_accessor :approved_at

    # Date and time the deposit was rejected.
    attr_accessor :rejected_at

    # Reason the deposit was rejected.
    attr_accessor :rejection_reason

    # Deposit transaction created on approval.
    attr_accessor :transaction_id

    # Moment the received Pix was recorded, before the credit.
    attr_accessor :created_at

    # Moment of the last change to the record, which changes when the deposit is approved or rejected.
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'status' => :'status',
        :'amount' => :'amount',
        :'payer_document' => :'payerDocument',
        :'payer_name' => :'payerName',
        :'payer_account_number' => :'payerAccountNumber',
        :'payer_institution_ispb' => :'payerInstitutionIspb',
        :'payer_institution_name' => :'payerInstitutionName',
        :'receiver_document' => :'receiverDocument',
        :'receiver_name' => :'receiverName',
        :'receiver_account_number' => :'receiverAccountNumber',
        :'receiver_institution_ispb' => :'receiverInstitutionIspb',
        :'receiver_institution_name' => :'receiverInstitutionName',
        :'end_to_end_id' => :'endToEndId',
        :'paid_at' => :'paidAt',
        :'pix_key' => :'pixKey',
        :'description' => :'description',
        :'approved_at' => :'approvedAt',
        :'rejected_at' => :'rejectedAt',
        :'rejection_reason' => :'rejectionReason',
        :'transaction_id' => :'transactionId',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'status' => :'String',
        :'amount' => :'Float',
        :'payer_document' => :'String',
        :'payer_name' => :'String',
        :'payer_account_number' => :'String',
        :'payer_institution_ispb' => :'String',
        :'payer_institution_name' => :'String',
        :'receiver_document' => :'String',
        :'receiver_name' => :'String',
        :'receiver_account_number' => :'String',
        :'receiver_institution_ispb' => :'String',
        :'receiver_institution_name' => :'String',
        :'end_to_end_id' => :'String',
        :'paid_at' => :'Time',
        :'pix_key' => :'String',
        :'description' => :'String',
        :'approved_at' => :'Time',
        :'rejected_at' => :'Time',
        :'rejection_reason' => :'String',
        :'transaction_id' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'payer_name',
        :'payer_account_number',
        :'payer_institution_ispb',
        :'payer_institution_name',
        :'receiver_document',
        :'receiver_name',
        :'receiver_account_number',
        :'receiver_institution_ispb',
        :'receiver_institution_name',
        :'paid_at',
        :'pix_key',
        :'description',
        :'approved_at',
        :'rejected_at',
        :'rejection_reason',
        :'transaction_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PayZuPix::DepositPending` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PayZuPix::DepositPending`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'payer_document')
        self.payer_document = attributes[:'payer_document']
      end

      if attributes.key?(:'payer_name')
        self.payer_name = attributes[:'payer_name']
      end

      if attributes.key?(:'payer_account_number')
        self.payer_account_number = attributes[:'payer_account_number']
      end

      if attributes.key?(:'payer_institution_ispb')
        self.payer_institution_ispb = attributes[:'payer_institution_ispb']
      end

      if attributes.key?(:'payer_institution_name')
        self.payer_institution_name = attributes[:'payer_institution_name']
      end

      if attributes.key?(:'receiver_document')
        self.receiver_document = attributes[:'receiver_document']
      end

      if attributes.key?(:'receiver_name')
        self.receiver_name = attributes[:'receiver_name']
      end

      if attributes.key?(:'receiver_account_number')
        self.receiver_account_number = attributes[:'receiver_account_number']
      end

      if attributes.key?(:'receiver_institution_ispb')
        self.receiver_institution_ispb = attributes[:'receiver_institution_ispb']
      end

      if attributes.key?(:'receiver_institution_name')
        self.receiver_institution_name = attributes[:'receiver_institution_name']
      end

      if attributes.key?(:'end_to_end_id')
        self.end_to_end_id = attributes[:'end_to_end_id']
      end

      if attributes.key?(:'paid_at')
        self.paid_at = attributes[:'paid_at']
      end

      if attributes.key?(:'pix_key')
        self.pix_key = attributes[:'pix_key']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'approved_at')
        self.approved_at = attributes[:'approved_at']
      end

      if attributes.key?(:'rejected_at')
        self.rejected_at = attributes[:'rejected_at']
      end

      if attributes.key?(:'rejection_reason')
        self.rejection_reason = attributes[:'rejection_reason']
      end

      if attributes.key?(:'transaction_id')
        self.transaction_id = attributes[:'transaction_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('String', ["PENDING", "APPROVED", "REJECTED", "EXPIRED", "COMPLETED"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          status == o.status &&
          amount == o.amount &&
          payer_document == o.payer_document &&
          payer_name == o.payer_name &&
          payer_account_number == o.payer_account_number &&
          payer_institution_ispb == o.payer_institution_ispb &&
          payer_institution_name == o.payer_institution_name &&
          receiver_document == o.receiver_document &&
          receiver_name == o.receiver_name &&
          receiver_account_number == o.receiver_account_number &&
          receiver_institution_ispb == o.receiver_institution_ispb &&
          receiver_institution_name == o.receiver_institution_name &&
          end_to_end_id == o.end_to_end_id &&
          paid_at == o.paid_at &&
          pix_key == o.pix_key &&
          description == o.description &&
          approved_at == o.approved_at &&
          rejected_at == o.rejected_at &&
          rejection_reason == o.rejection_reason &&
          transaction_id == o.transaction_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, status, amount, payer_document, payer_name, payer_account_number, payer_institution_ispb, payer_institution_name, receiver_document, receiver_name, receiver_account_number, receiver_institution_ispb, receiver_institution_name, end_to_end_id, paid_at, pix_key, description, approved_at, rejected_at, rejection_reason, transaction_id, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
