=begin
#PayZu Pix API

#REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v3`  Repo: https://github.com/PayZuAI/payzu-sdks 

The version of the OpenAPI document: 1.8.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module PayZuPix
  # Cash-in and cash-out fees of the account, in reais.
  class GetUser200ResponseServiceFee < ApiModelBase
    # Floor of the cash-in fee, in reais.
    attr_accessor :cash_in_minimum

    # Fixed part of the cash-in fee, in reais.
    attr_accessor :cash_in_fixed

    # Percentage of the cash-in fee.
    attr_accessor :cash_in_percent

    # Floor of the withdrawal fee, in reais.
    attr_accessor :cash_out_minimum

    # Fixed part of the withdrawal fee, in reais.
    attr_accessor :cash_out_fixed

    # Percentage of the withdrawal fee.
    attr_accessor :cash_out_percent

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cash_in_minimum' => :'cashInMinimum',
        :'cash_in_fixed' => :'cashInFixed',
        :'cash_in_percent' => :'cashInPercent',
        :'cash_out_minimum' => :'cashOutMinimum',
        :'cash_out_fixed' => :'cashOutFixed',
        :'cash_out_percent' => :'cashOutPercent'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cash_in_minimum' => :'Float',
        :'cash_in_fixed' => :'Float',
        :'cash_in_percent' => :'Float',
        :'cash_out_minimum' => :'Float',
        :'cash_out_fixed' => :'Float',
        :'cash_out_percent' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PayZuPix::GetUser200ResponseServiceFee` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PayZuPix::GetUser200ResponseServiceFee`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cash_in_minimum')
        self.cash_in_minimum = attributes[:'cash_in_minimum']
      end

      if attributes.key?(:'cash_in_fixed')
        self.cash_in_fixed = attributes[:'cash_in_fixed']
      end

      if attributes.key?(:'cash_in_percent')
        self.cash_in_percent = attributes[:'cash_in_percent']
      end

      if attributes.key?(:'cash_out_minimum')
        self.cash_out_minimum = attributes[:'cash_out_minimum']
      end

      if attributes.key?(:'cash_out_fixed')
        self.cash_out_fixed = attributes[:'cash_out_fixed']
      end

      if attributes.key?(:'cash_out_percent')
        self.cash_out_percent = attributes[:'cash_out_percent']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cash_in_minimum == o.cash_in_minimum &&
          cash_in_fixed == o.cash_in_fixed &&
          cash_in_percent == o.cash_in_percent &&
          cash_out_minimum == o.cash_out_minimum &&
          cash_out_fixed == o.cash_out_fixed &&
          cash_out_percent == o.cash_out_percent
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cash_in_minimum, cash_in_fixed, cash_in_percent, cash_out_minimum, cash_out_fixed, cash_out_percent].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
