=begin
#PayZu Pix API

#REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v3`  Repo: https://github.com/PayZuAI/payzu-sdks 

The version of the OpenAPI document: 1.8.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'payzu-pix/api_client'
require 'payzu-pix/api_error'
require 'payzu-pix/api_model_base'
require 'payzu-pix/version'
require 'payzu-pix/configuration'

# Models
require 'payzu-pix/models/api_error_details_inner'
require 'payzu-pix/models/bank_statement'
require 'payzu-pix/models/bank_statement_list_response'
require 'payzu-pix/models/bank_statement_list_response_pagination'
require 'payzu-pix/models/callback_detail'
require 'payzu-pix/models/callback_list_response'
require 'payzu-pix/models/callback_list_response_pagination'
require 'payzu-pix/models/callback_secret_response'
require 'payzu-pix/models/defense'
require 'payzu-pix/models/defense_files_inner'
require 'payzu-pix/models/defense_history_entry'
require 'payzu-pix/models/defense_history_entry_files_inner'
require 'payzu-pix/models/deposit_pending'
require 'payzu-pix/models/deposit_pending_list_response'
require 'payzu-pix/models/dict_consult_response'
require 'payzu-pix/models/download_user_report200_response'
require 'payzu-pix/models/enqueued_callback'
require 'payzu-pix/models/enqueued_callback_enqueued'
require 'payzu-pix/models/enqueued_callback_item'
require 'payzu-pix/models/error_response'
require 'payzu-pix/models/get_user200_response'
require 'payzu-pix/models/get_user200_response_daily_withdraw_limit'
require 'payzu-pix/models/get_user200_response_service_fee'
require 'payzu-pix/models/get_user_balance200_response'
require 'payzu-pix/models/get_user_transaction_by_id200_response'
require 'payzu-pix/models/get_user_transaction_by_id200_response_all_of_callback_log_inner'
require 'payzu-pix/models/get_user_transaction_by_id200_response_all_of_infraction_inner'
require 'payzu-pix/models/get_user_transactions200_response'
require 'payzu-pix/models/infraction_detail'
require 'payzu-pix/models/infraction_detail_transaction'
require 'payzu-pix/models/infraction_list_response'
require 'payzu-pix/models/infraction_list_response_pagination'
require 'payzu-pix/models/list_user_reports200_response'
require 'payzu-pix/models/pix_key_info'
require 'payzu-pix/models/post_internal_transfer_request'
require 'payzu-pix/models/post_pix_qrcode_read_request'
require 'payzu-pix/models/post_pix_request'
require 'payzu-pix/models/post_user_report_request'
require 'payzu-pix/models/post_withdraw_qrcode_request'
require 'payzu-pix/models/post_withdraw_request'
require 'payzu-pix/models/proof_response'
require 'payzu-pix/models/qr_code_read_response'
require 'payzu-pix/models/refund'
require 'payzu-pix/models/refund_request'
require 'payzu-pix/models/report_job'
require 'payzu-pix/models/report_job_accepted'
require 'payzu-pix/models/report_job_detail'
require 'payzu-pix/models/resend_user_callback_single200_response'
require 'payzu-pix/models/resend_user_callbacks200_response'
require 'payzu-pix/models/resend_user_callbacks_request'
require 'payzu-pix/models/resend_webhook_callbacks_request'
require 'payzu-pix/models/rotate_callback_secret_response'
require 'payzu-pix/models/rotate_secret_response'
require 'payzu-pix/models/sent_webhook_detail'
require 'payzu-pix/models/sent_webhook_detail_response'
require 'payzu-pix/models/sent_webhooks_quantity'
require 'payzu-pix/models/summary'
require 'payzu-pix/models/summary_block'
require 'payzu-pix/models/summary_block_grouped_inner'
require 'payzu-pix/models/summary_block_statuses'
require 'payzu-pix/models/summary_status'
require 'payzu-pix/models/transaction'
require 'payzu-pix/models/transaction_with_refunds'
require 'payzu-pix/models/webhook'
require 'payzu-pix/models/webhook_create_request'
require 'payzu-pix/models/webhook_event_type'
require 'payzu-pix/models/webhook_list_response'
require 'payzu-pix/models/webhook_update_request'
require 'payzu-pix/models/webhook_with_secret'

# APIs
require 'payzu-pix/api/account_api'
require 'payzu-pix/api/callbacks_api'
require 'payzu-pix/api/infractions_api'
require 'payzu-pix/api/internal_transfer_api'
require 'payzu-pix/api/keys_and_dict_api'
require 'payzu-pix/api/pix_operations_api'
require 'payzu-pix/api/refunds_api'
require 'payzu-pix/api/reports_api'
require 'payzu-pix/api/webhooks_api'
require 'payzu-pix/api/withdrawals_api'

module PayZuPix
  class << self
    # Customize default settings for the SDK using block.
    #   PayZuPix.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
