# coding: utf-8

"""
    PayZu Pix API

    REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v3`  Repo: https://github.com/PayZuAI/payzu-sdks 

    The version of the OpenAPI document: 1.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Refund(BaseModel):
    """
    Refund
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Refund identifier.")
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Refunded amount in BRL.")
    reason: Optional[StrictStr] = Field(default=None, description="Refund reason.")
    description: Optional[StrictStr] = Field(default=None, description="Refund description.")
    status: Optional[StrictStr] = Field(default=None, description="Refund status.")
    end_to_end_id: Optional[StrictStr] = Field(default=None, description="End-to-end ID of the refund Pix.", alias="endToEndId")
    refunded_at: Optional[datetime] = Field(default=None, description="When the refund was completed.", alias="refundedAt")
    created_at: Optional[datetime] = Field(default=None, description="When the refund was requested.", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last change to the refund.", alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "amount", "reason", "description", "status", "endToEndId", "refundedAt", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Refund from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if end_to_end_id (nullable) is None
        # and model_fields_set contains the field
        if self.end_to_end_id is None and "end_to_end_id" in self.model_fields_set:
            _dict['endToEndId'] = None

        # set to None if refunded_at (nullable) is None
        # and model_fields_set contains the field
        if self.refunded_at is None and "refunded_at" in self.model_fields_set:
            _dict['refundedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Refund from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "amount": obj.get("amount"),
            "reason": obj.get("reason"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "endToEndId": obj.get("endToEndId"),
            "refundedAt": obj.get("refundedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


