generatorName: go
outputDir: go
gitUserId: PayZuAI
gitRepoId: payzu-sdks/go/v2
nameMappings:
  hasSecret: HasSecretConfigured
additionalProperties:
  enumUnknownDefaultCase: true
  packageName: payzupix
  packageVersion: 2.0.0
globalProperties:
  apiTests: false
  modelTests: false
