/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - Go: `go get github.com/PayZuAI/payzu-sdks/go` - PHP: `composer require payzu/pix`  Repo: https://github.com/PayZuAI/payzu-sdks 

API version: 1.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
)

// checks if the Summary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Summary{}

// Summary struct for Summary
type Summary struct {
	TotalTransactions *int32 `json:"totalTransactions,omitempty"`
	Deposit *SummaryBlock `json:"deposit,omitempty"`
	Withdraw *SummaryBlock `json:"withdraw,omitempty"`
	Commission *SummaryBlock `json:"commission,omitempty"`
}

// NewSummary instantiates a new Summary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummary() *Summary {
	this := Summary{}
	return &this
}

// NewSummaryWithDefaults instantiates a new Summary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryWithDefaults() *Summary {
	this := Summary{}
	return &this
}

// GetTotalTransactions returns the TotalTransactions field value if set, zero value otherwise.
func (o *Summary) GetTotalTransactions() int32 {
	if o == nil || IsNil(o.TotalTransactions) {
		var ret int32
		return ret
	}
	return *o.TotalTransactions
}

// GetTotalTransactionsOk returns a tuple with the TotalTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetTotalTransactionsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTransactions) {
		return nil, false
	}
	return o.TotalTransactions, true
}

// HasTotalTransactions returns a boolean if a field has been set.
func (o *Summary) HasTotalTransactions() bool {
	if o != nil && !IsNil(o.TotalTransactions) {
		return true
	}

	return false
}

// SetTotalTransactions gets a reference to the given int32 and assigns it to the TotalTransactions field.
func (o *Summary) SetTotalTransactions(v int32) {
	o.TotalTransactions = &v
}

// GetDeposit returns the Deposit field value if set, zero value otherwise.
func (o *Summary) GetDeposit() SummaryBlock {
	if o == nil || IsNil(o.Deposit) {
		var ret SummaryBlock
		return ret
	}
	return *o.Deposit
}

// GetDepositOk returns a tuple with the Deposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetDepositOk() (*SummaryBlock, bool) {
	if o == nil || IsNil(o.Deposit) {
		return nil, false
	}
	return o.Deposit, true
}

// HasDeposit returns a boolean if a field has been set.
func (o *Summary) HasDeposit() bool {
	if o != nil && !IsNil(o.Deposit) {
		return true
	}

	return false
}

// SetDeposit gets a reference to the given SummaryBlock and assigns it to the Deposit field.
func (o *Summary) SetDeposit(v SummaryBlock) {
	o.Deposit = &v
}

// GetWithdraw returns the Withdraw field value if set, zero value otherwise.
func (o *Summary) GetWithdraw() SummaryBlock {
	if o == nil || IsNil(o.Withdraw) {
		var ret SummaryBlock
		return ret
	}
	return *o.Withdraw
}

// GetWithdrawOk returns a tuple with the Withdraw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetWithdrawOk() (*SummaryBlock, bool) {
	if o == nil || IsNil(o.Withdraw) {
		return nil, false
	}
	return o.Withdraw, true
}

// HasWithdraw returns a boolean if a field has been set.
func (o *Summary) HasWithdraw() bool {
	if o != nil && !IsNil(o.Withdraw) {
		return true
	}

	return false
}

// SetWithdraw gets a reference to the given SummaryBlock and assigns it to the Withdraw field.
func (o *Summary) SetWithdraw(v SummaryBlock) {
	o.Withdraw = &v
}

// GetCommission returns the Commission field value if set, zero value otherwise.
func (o *Summary) GetCommission() SummaryBlock {
	if o == nil || IsNil(o.Commission) {
		var ret SummaryBlock
		return ret
	}
	return *o.Commission
}

// GetCommissionOk returns a tuple with the Commission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetCommissionOk() (*SummaryBlock, bool) {
	if o == nil || IsNil(o.Commission) {
		return nil, false
	}
	return o.Commission, true
}

// HasCommission returns a boolean if a field has been set.
func (o *Summary) HasCommission() bool {
	if o != nil && !IsNil(o.Commission) {
		return true
	}

	return false
}

// SetCommission gets a reference to the given SummaryBlock and assigns it to the Commission field.
func (o *Summary) SetCommission(v SummaryBlock) {
	o.Commission = &v
}

func (o Summary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Summary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalTransactions) {
		toSerialize["totalTransactions"] = o.TotalTransactions
	}
	if !IsNil(o.Deposit) {
		toSerialize["deposit"] = o.Deposit
	}
	if !IsNil(o.Withdraw) {
		toSerialize["withdraw"] = o.Withdraw
	}
	if !IsNil(o.Commission) {
		toSerialize["commission"] = o.Commission
	}
	return toSerialize, nil
}

type NullableSummary struct {
	value *Summary
	isSet bool
}

func (v NullableSummary) Get() *Summary {
	return v.value
}

func (v *NullableSummary) Set(val *Summary) {
	v.value = val
	v.isSet = true
}

func (v NullableSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummary(val *Summary) *NullableSummary {
	return &NullableSummary{value: val, isSet: true}
}

func (v NullableSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


