/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go`  Repo: https://github.com/PayZuAI/payzu-sdks 

API version: 1.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"time"
)

// checks if the ReportJobDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportJobDetail{}

// ReportJobDetail Report job with the filters used and the total of rows written.
type ReportJobDetail struct {
	// Report identifier (UUID), generated when the report is requested.
	Id *string `json:"id,omitempty"`
	// Generation progress: PENDING, RUNNING, COMPLETED or FAILED.
	Status *string `json:"status,omitempty"`
	// Date and time the report generation was requested.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Date and time of the last change to the report record.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// When the file expires from storage (usually 7 days after creation)
	ExpiresAt NullableTime `json:"expiresAt,omitempty"`
	// Filters used when the report was created.
	Params map[string]interface{} `json:"params,omitempty"`
	// Rows written to the file. Null until the report is COMPLETED.
	WrittenRows NullableInt32 `json:"writtenRows,omitempty"`
}

// NewReportJobDetail instantiates a new ReportJobDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportJobDetail() *ReportJobDetail {
	this := ReportJobDetail{}
	return &this
}

// NewReportJobDetailWithDefaults instantiates a new ReportJobDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportJobDetailWithDefaults() *ReportJobDetail {
	this := ReportJobDetail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReportJobDetail) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportJobDetail) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReportJobDetail) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReportJobDetail) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReportJobDetail) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportJobDetail) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReportJobDetail) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ReportJobDetail) SetStatus(v string) {
	o.Status = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ReportJobDetail) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportJobDetail) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ReportJobDetail) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ReportJobDetail) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ReportJobDetail) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportJobDetail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ReportJobDetail) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ReportJobDetail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReportJobDetail) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportJobDetail) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ReportJobDetail) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *ReportJobDetail) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *ReportJobDetail) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *ReportJobDetail) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *ReportJobDetail) GetParams() map[string]interface{} {
	if o == nil || IsNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportJobDetail) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *ReportJobDetail) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *ReportJobDetail) SetParams(v map[string]interface{}) {
	o.Params = v
}

// GetWrittenRows returns the WrittenRows field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReportJobDetail) GetWrittenRows() int32 {
	if o == nil || IsNil(o.WrittenRows.Get()) {
		var ret int32
		return ret
	}
	return *o.WrittenRows.Get()
}

// GetWrittenRowsOk returns a tuple with the WrittenRows field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportJobDetail) GetWrittenRowsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WrittenRows.Get(), o.WrittenRows.IsSet()
}

// HasWrittenRows returns a boolean if a field has been set.
func (o *ReportJobDetail) HasWrittenRows() bool {
	if o != nil && o.WrittenRows.IsSet() {
		return true
	}

	return false
}

// SetWrittenRows gets a reference to the given NullableInt32 and assigns it to the WrittenRows field.
func (o *ReportJobDetail) SetWrittenRows(v int32) {
	o.WrittenRows.Set(&v)
}
// SetWrittenRowsNil sets the value for WrittenRows to be an explicit nil
func (o *ReportJobDetail) SetWrittenRowsNil() {
	o.WrittenRows.Set(nil)
}

// UnsetWrittenRows ensures that no value is present for WrittenRows, not even an explicit nil
func (o *ReportJobDetail) UnsetWrittenRows() {
	o.WrittenRows.Unset()
}

func (o ReportJobDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportJobDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expiresAt"] = o.ExpiresAt.Get()
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	if o.WrittenRows.IsSet() {
		toSerialize["writtenRows"] = o.WrittenRows.Get()
	}
	return toSerialize, nil
}

type NullableReportJobDetail struct {
	value *ReportJobDetail
	isSet bool
}

func (v NullableReportJobDetail) Get() *ReportJobDetail {
	return v.value
}

func (v *NullableReportJobDetail) Set(val *ReportJobDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableReportJobDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableReportJobDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportJobDetail(val *ReportJobDetail) *NullableReportJobDetail {
	return &NullableReportJobDetail{value: val, isSet: true}
}

func (v NullableReportJobDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportJobDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


