/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v2`  Repo: https://github.com/PayZuAI/payzu-sdks 

API version: 1.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"time"
)

// checks if the WebhookWithSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookWithSecret{}

// WebhookWithSecret struct for WebhookWithSecret
type WebhookWithSecret struct {
	// Webhook identifier.
	Id *string `json:"id,omitempty"`
	// Address that receives the notifications.
	Url *string `json:"url,omitempty"`
	// Indicates whether the webhook starts out receiving events.
	Active *bool `json:"active,omitempty"`
	// Events subscribed by this webhook.
	Events []WebhookEventType `json:"events,omitempty"`
	// Indicates whether the webhook has a signing secret.
	HasSecretConfigured *bool `json:"hasSecret,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Date and time of the last change to the webhook.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// HMAC signing secret. Shown only on creation and on rotate-secret. Store it now.
	Secret NullableString `json:"secret,omitempty"`
}

// NewWebhookWithSecret instantiates a new WebhookWithSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookWithSecret() *WebhookWithSecret {
	this := WebhookWithSecret{}
	return &this
}

// NewWebhookWithSecretWithDefaults instantiates a new WebhookWithSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookWithSecretWithDefaults() *WebhookWithSecret {
	this := WebhookWithSecret{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WebhookWithSecret) SetId(v string) {
	o.Id = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebhookWithSecret) SetUrl(v string) {
	o.Url = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *WebhookWithSecret) SetActive(v bool) {
	o.Active = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetEvents() []WebhookEventType {
	if o == nil || IsNil(o.Events) {
		var ret []WebhookEventType
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetEventsOk() ([]WebhookEventType, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []WebhookEventType and assigns it to the Events field.
func (o *WebhookWithSecret) SetEvents(v []WebhookEventType) {
	o.Events = v
}

// GetHasSecretConfigured returns the HasSecretConfigured field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetHasSecretConfigured() bool {
	if o == nil || IsNil(o.HasSecretConfigured) {
		var ret bool
		return ret
	}
	return *o.HasSecretConfigured
}

// GetHasSecretConfiguredOk returns a tuple with the HasSecretConfigured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetHasSecretConfiguredOk() (*bool, bool) {
	if o == nil || IsNil(o.HasSecretConfigured) {
		return nil, false
	}
	return o.HasSecretConfigured, true
}

// HasHasSecretConfigured returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasHasSecretConfigured() bool {
	if o != nil && !IsNil(o.HasSecretConfigured) {
		return true
	}

	return false
}

// SetHasSecretConfigured gets a reference to the given bool and assigns it to the HasSecretConfigured field.
func (o *WebhookWithSecret) SetHasSecretConfigured(v bool) {
	o.HasSecretConfigured = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WebhookWithSecret) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WebhookWithSecret) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookWithSecret) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *WebhookWithSecret) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookWithSecret) GetSecret() string {
	if o == nil || IsNil(o.Secret.Get()) {
		var ret string
		return ret
	}
	return *o.Secret.Get()
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookWithSecret) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secret.Get(), o.Secret.IsSet()
}

// HasSecret returns a boolean if a field has been set.
func (o *WebhookWithSecret) HasSecret() bool {
	if o != nil && o.Secret.IsSet() {
		return true
	}

	return false
}

// SetSecret gets a reference to the given NullableString and assigns it to the Secret field.
func (o *WebhookWithSecret) SetSecret(v string) {
	o.Secret.Set(&v)
}
// SetSecretNil sets the value for Secret to be an explicit nil
func (o *WebhookWithSecret) SetSecretNil() {
	o.Secret.Set(nil)
}

// UnsetSecret ensures that no value is present for Secret, not even an explicit nil
func (o *WebhookWithSecret) UnsetSecret() {
	o.Secret.Unset()
}

func (o WebhookWithSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookWithSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.HasSecretConfigured) {
		toSerialize["hasSecret"] = o.HasSecretConfigured
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.Secret.IsSet() {
		toSerialize["secret"] = o.Secret.Get()
	}
	return toSerialize, nil
}

type NullableWebhookWithSecret struct {
	value *WebhookWithSecret
	isSet bool
}

func (v NullableWebhookWithSecret) Get() *WebhookWithSecret {
	return v.value
}

func (v *NullableWebhookWithSecret) Set(val *WebhookWithSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookWithSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookWithSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookWithSecret(val *WebhookWithSecret) *NullableWebhookWithSecret {
	return &NullableWebhookWithSecret{value: val, isSet: true}
}

func (v NullableWebhookWithSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookWithSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


