/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v2`  Repo: https://github.com/PayZuAI/payzu-sdks 

API version: 1.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"time"
)

// checks if the BankStatement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankStatement{}

// BankStatement struct for BankStatement
type BankStatement struct {
	// Identifier of the balance entry.
	Id *string `json:"id,omitempty"`
	// Amount of the entry.
	Amount *float32 `json:"amount,omitempty"`
	// INCREMENT credits the balance, DECREMENT debits it.
	Operation *string `json:"operation,omitempty"`
	// Reason for the ledger entry.
	Reason *string `json:"reason,omitempty"`
	// Balance moved: AVAILABLE or BLOCKED.
	BalanceType *string `json:"balanceType,omitempty"`
	// Balance free for use that the account had, in reais, immediately before this entry.
	PreviousBalanceAvailable *float32 `json:"previousBalanceAvailable,omitempty"`
	// Blocked balance before the entry, in reais.
	PreviousBalanceBlocked *float32 `json:"previousBalanceBlocked,omitempty"`
	// Available balance after the entry, in reais.
	NewBalanceAvailable *float32 `json:"newBalanceAvailable,omitempty"`
	// Blocked balance after the entry, in reais.
	NewBalanceBlocked *float32 `json:"newBalanceBlocked,omitempty"`
	// Transaction that originated the entry.
	TransactionId NullableString `json:"transactionId,omitempty"`
	// Infraction related to the entry.
	InfractionId NullableString `json:"infractionId,omitempty"`
	// Date and time the balance movement was recorded.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Date and time of the last change to the record.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewBankStatement instantiates a new BankStatement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankStatement() *BankStatement {
	this := BankStatement{}
	return &this
}

// NewBankStatementWithDefaults instantiates a new BankStatement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankStatementWithDefaults() *BankStatement {
	this := BankStatement{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BankStatement) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BankStatement) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BankStatement) SetId(v string) {
	o.Id = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *BankStatement) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *BankStatement) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *BankStatement) SetAmount(v float32) {
	o.Amount = &v
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *BankStatement) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *BankStatement) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *BankStatement) SetOperation(v string) {
	o.Operation = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BankStatement) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BankStatement) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BankStatement) SetReason(v string) {
	o.Reason = &v
}

// GetBalanceType returns the BalanceType field value if set, zero value otherwise.
func (o *BankStatement) GetBalanceType() string {
	if o == nil || IsNil(o.BalanceType) {
		var ret string
		return ret
	}
	return *o.BalanceType
}

// GetBalanceTypeOk returns a tuple with the BalanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetBalanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BalanceType) {
		return nil, false
	}
	return o.BalanceType, true
}

// HasBalanceType returns a boolean if a field has been set.
func (o *BankStatement) HasBalanceType() bool {
	if o != nil && !IsNil(o.BalanceType) {
		return true
	}

	return false
}

// SetBalanceType gets a reference to the given string and assigns it to the BalanceType field.
func (o *BankStatement) SetBalanceType(v string) {
	o.BalanceType = &v
}

// GetPreviousBalanceAvailable returns the PreviousBalanceAvailable field value if set, zero value otherwise.
func (o *BankStatement) GetPreviousBalanceAvailable() float32 {
	if o == nil || IsNil(o.PreviousBalanceAvailable) {
		var ret float32
		return ret
	}
	return *o.PreviousBalanceAvailable
}

// GetPreviousBalanceAvailableOk returns a tuple with the PreviousBalanceAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetPreviousBalanceAvailableOk() (*float32, bool) {
	if o == nil || IsNil(o.PreviousBalanceAvailable) {
		return nil, false
	}
	return o.PreviousBalanceAvailable, true
}

// HasPreviousBalanceAvailable returns a boolean if a field has been set.
func (o *BankStatement) HasPreviousBalanceAvailable() bool {
	if o != nil && !IsNil(o.PreviousBalanceAvailable) {
		return true
	}

	return false
}

// SetPreviousBalanceAvailable gets a reference to the given float32 and assigns it to the PreviousBalanceAvailable field.
func (o *BankStatement) SetPreviousBalanceAvailable(v float32) {
	o.PreviousBalanceAvailable = &v
}

// GetPreviousBalanceBlocked returns the PreviousBalanceBlocked field value if set, zero value otherwise.
func (o *BankStatement) GetPreviousBalanceBlocked() float32 {
	if o == nil || IsNil(o.PreviousBalanceBlocked) {
		var ret float32
		return ret
	}
	return *o.PreviousBalanceBlocked
}

// GetPreviousBalanceBlockedOk returns a tuple with the PreviousBalanceBlocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetPreviousBalanceBlockedOk() (*float32, bool) {
	if o == nil || IsNil(o.PreviousBalanceBlocked) {
		return nil, false
	}
	return o.PreviousBalanceBlocked, true
}

// HasPreviousBalanceBlocked returns a boolean if a field has been set.
func (o *BankStatement) HasPreviousBalanceBlocked() bool {
	if o != nil && !IsNil(o.PreviousBalanceBlocked) {
		return true
	}

	return false
}

// SetPreviousBalanceBlocked gets a reference to the given float32 and assigns it to the PreviousBalanceBlocked field.
func (o *BankStatement) SetPreviousBalanceBlocked(v float32) {
	o.PreviousBalanceBlocked = &v
}

// GetNewBalanceAvailable returns the NewBalanceAvailable field value if set, zero value otherwise.
func (o *BankStatement) GetNewBalanceAvailable() float32 {
	if o == nil || IsNil(o.NewBalanceAvailable) {
		var ret float32
		return ret
	}
	return *o.NewBalanceAvailable
}

// GetNewBalanceAvailableOk returns a tuple with the NewBalanceAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetNewBalanceAvailableOk() (*float32, bool) {
	if o == nil || IsNil(o.NewBalanceAvailable) {
		return nil, false
	}
	return o.NewBalanceAvailable, true
}

// HasNewBalanceAvailable returns a boolean if a field has been set.
func (o *BankStatement) HasNewBalanceAvailable() bool {
	if o != nil && !IsNil(o.NewBalanceAvailable) {
		return true
	}

	return false
}

// SetNewBalanceAvailable gets a reference to the given float32 and assigns it to the NewBalanceAvailable field.
func (o *BankStatement) SetNewBalanceAvailable(v float32) {
	o.NewBalanceAvailable = &v
}

// GetNewBalanceBlocked returns the NewBalanceBlocked field value if set, zero value otherwise.
func (o *BankStatement) GetNewBalanceBlocked() float32 {
	if o == nil || IsNil(o.NewBalanceBlocked) {
		var ret float32
		return ret
	}
	return *o.NewBalanceBlocked
}

// GetNewBalanceBlockedOk returns a tuple with the NewBalanceBlocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetNewBalanceBlockedOk() (*float32, bool) {
	if o == nil || IsNil(o.NewBalanceBlocked) {
		return nil, false
	}
	return o.NewBalanceBlocked, true
}

// HasNewBalanceBlocked returns a boolean if a field has been set.
func (o *BankStatement) HasNewBalanceBlocked() bool {
	if o != nil && !IsNil(o.NewBalanceBlocked) {
		return true
	}

	return false
}

// SetNewBalanceBlocked gets a reference to the given float32 and assigns it to the NewBalanceBlocked field.
func (o *BankStatement) SetNewBalanceBlocked(v float32) {
	o.NewBalanceBlocked = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankStatement) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId.Get()) {
		var ret string
		return ret
	}
	return *o.TransactionId.Get()
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankStatement) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionId.Get(), o.TransactionId.IsSet()
}

// HasTransactionId returns a boolean if a field has been set.
func (o *BankStatement) HasTransactionId() bool {
	if o != nil && o.TransactionId.IsSet() {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given NullableString and assigns it to the TransactionId field.
func (o *BankStatement) SetTransactionId(v string) {
	o.TransactionId.Set(&v)
}
// SetTransactionIdNil sets the value for TransactionId to be an explicit nil
func (o *BankStatement) SetTransactionIdNil() {
	o.TransactionId.Set(nil)
}

// UnsetTransactionId ensures that no value is present for TransactionId, not even an explicit nil
func (o *BankStatement) UnsetTransactionId() {
	o.TransactionId.Unset()
}

// GetInfractionId returns the InfractionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankStatement) GetInfractionId() string {
	if o == nil || IsNil(o.InfractionId.Get()) {
		var ret string
		return ret
	}
	return *o.InfractionId.Get()
}

// GetInfractionIdOk returns a tuple with the InfractionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankStatement) GetInfractionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InfractionId.Get(), o.InfractionId.IsSet()
}

// HasInfractionId returns a boolean if a field has been set.
func (o *BankStatement) HasInfractionId() bool {
	if o != nil && o.InfractionId.IsSet() {
		return true
	}

	return false
}

// SetInfractionId gets a reference to the given NullableString and assigns it to the InfractionId field.
func (o *BankStatement) SetInfractionId(v string) {
	o.InfractionId.Set(&v)
}
// SetInfractionIdNil sets the value for InfractionId to be an explicit nil
func (o *BankStatement) SetInfractionIdNil() {
	o.InfractionId.Set(nil)
}

// UnsetInfractionId ensures that no value is present for InfractionId, not even an explicit nil
func (o *BankStatement) UnsetInfractionId() {
	o.InfractionId.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BankStatement) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BankStatement) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *BankStatement) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *BankStatement) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankStatement) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BankStatement) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *BankStatement) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o BankStatement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankStatement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.BalanceType) {
		toSerialize["balanceType"] = o.BalanceType
	}
	if !IsNil(o.PreviousBalanceAvailable) {
		toSerialize["previousBalanceAvailable"] = o.PreviousBalanceAvailable
	}
	if !IsNil(o.PreviousBalanceBlocked) {
		toSerialize["previousBalanceBlocked"] = o.PreviousBalanceBlocked
	}
	if !IsNil(o.NewBalanceAvailable) {
		toSerialize["newBalanceAvailable"] = o.NewBalanceAvailable
	}
	if !IsNil(o.NewBalanceBlocked) {
		toSerialize["newBalanceBlocked"] = o.NewBalanceBlocked
	}
	if o.TransactionId.IsSet() {
		toSerialize["transactionId"] = o.TransactionId.Get()
	}
	if o.InfractionId.IsSet() {
		toSerialize["infractionId"] = o.InfractionId.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableBankStatement struct {
	value *BankStatement
	isSet bool
}

func (v NullableBankStatement) Get() *BankStatement {
	return v.value
}

func (v *NullableBankStatement) Set(val *BankStatement) {
	v.value = val
	v.isSet = true
}

func (v NullableBankStatement) IsSet() bool {
	return v.isSet
}

func (v *NullableBankStatement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankStatement(val *BankStatement) *NullableBankStatement {
	return &NullableBankStatement{value: val, isSet: true}
}

func (v NullableBankStatement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankStatement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


