/*
PayZu Pix API

REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v2`  Repo: https://github.com/PayZuAI/payzu-sdks 

API version: 1.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payzupix

import (
	"encoding/json"
	"time"
)

// checks if the GetUser200ResponseDailyWithdrawLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUser200ResponseDailyWithdrawLimit{}

// GetUser200ResponseDailyWithdrawLimit Control of the daily outbound cap.
type GetUser200ResponseDailyWithdrawLimit struct {
	// Daily outbound cap, in reais, summing withdrawals and internal transfers.
	Limit *float32 `json:"limit,omitempty"`
	// Total of the cap consumed in the day, in reais, by withdrawals and internal transfers.
	Used *float32 `json:"used,omitempty"`
	// Date and time of the last change to the daily limit.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Moment of the last reset of the daily usage.
	LastReset NullableTime `json:"lastReset,omitempty"`
}

// NewGetUser200ResponseDailyWithdrawLimit instantiates a new GetUser200ResponseDailyWithdrawLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUser200ResponseDailyWithdrawLimit() *GetUser200ResponseDailyWithdrawLimit {
	this := GetUser200ResponseDailyWithdrawLimit{}
	return &this
}

// NewGetUser200ResponseDailyWithdrawLimitWithDefaults instantiates a new GetUser200ResponseDailyWithdrawLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUser200ResponseDailyWithdrawLimitWithDefaults() *GetUser200ResponseDailyWithdrawLimit {
	this := GetUser200ResponseDailyWithdrawLimit{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetUser200ResponseDailyWithdrawLimit) GetLimit() float32 {
	if o == nil || IsNil(o.Limit) {
		var ret float32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) GetLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given float32 and assigns it to the Limit field.
func (o *GetUser200ResponseDailyWithdrawLimit) SetLimit(v float32) {
	o.Limit = &v
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *GetUser200ResponseDailyWithdrawLimit) GetUsed() float32 {
	if o == nil || IsNil(o.Used) {
		var ret float32
		return ret
	}
	return *o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) GetUsedOk() (*float32, bool) {
	if o == nil || IsNil(o.Used) {
		return nil, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given float32 and assigns it to the Used field.
func (o *GetUser200ResponseDailyWithdrawLimit) SetUsed(v float32) {
	o.Used = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetUser200ResponseDailyWithdrawLimit) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetUser200ResponseDailyWithdrawLimit) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetLastReset returns the LastReset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetUser200ResponseDailyWithdrawLimit) GetLastReset() time.Time {
	if o == nil || IsNil(o.LastReset.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastReset.Get()
}

// GetLastResetOk returns a tuple with the LastReset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetUser200ResponseDailyWithdrawLimit) GetLastResetOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastReset.Get(), o.LastReset.IsSet()
}

// HasLastReset returns a boolean if a field has been set.
func (o *GetUser200ResponseDailyWithdrawLimit) HasLastReset() bool {
	if o != nil && o.LastReset.IsSet() {
		return true
	}

	return false
}

// SetLastReset gets a reference to the given NullableTime and assigns it to the LastReset field.
func (o *GetUser200ResponseDailyWithdrawLimit) SetLastReset(v time.Time) {
	o.LastReset.Set(&v)
}
// SetLastResetNil sets the value for LastReset to be an explicit nil
func (o *GetUser200ResponseDailyWithdrawLimit) SetLastResetNil() {
	o.LastReset.Set(nil)
}

// UnsetLastReset ensures that no value is present for LastReset, not even an explicit nil
func (o *GetUser200ResponseDailyWithdrawLimit) UnsetLastReset() {
	o.LastReset.Unset()
}

func (o GetUser200ResponseDailyWithdrawLimit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUser200ResponseDailyWithdrawLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.LastReset.IsSet() {
		toSerialize["lastReset"] = o.LastReset.Get()
	}
	return toSerialize, nil
}

type NullableGetUser200ResponseDailyWithdrawLimit struct {
	value *GetUser200ResponseDailyWithdrawLimit
	isSet bool
}

func (v NullableGetUser200ResponseDailyWithdrawLimit) Get() *GetUser200ResponseDailyWithdrawLimit {
	return v.value
}

func (v *NullableGetUser200ResponseDailyWithdrawLimit) Set(val *GetUser200ResponseDailyWithdrawLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUser200ResponseDailyWithdrawLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUser200ResponseDailyWithdrawLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUser200ResponseDailyWithdrawLimit(val *GetUser200ResponseDailyWithdrawLimit) *NullableGetUser200ResponseDailyWithdrawLimit {
	return &NullableGetUser200ResponseDailyWithdrawLimit{value: val, isSet: true}
}

func (v NullableGetUser200ResponseDailyWithdrawLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUser200ResponseDailyWithdrawLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


