/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import br.com.payzu.pix.model.ApiErrorDetailsInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * ApiError
 */
@JsonPropertyOrder({
  ApiError.JSON_PROPERTY_STATUS,
  ApiError.JSON_PROPERTY_ERROR,
  ApiError.JSON_PROPERTY_ERROR_CODE,
  ApiError.JSON_PROPERTY_MESSAGE,
  ApiError.JSON_PROPERTY_STATUS_CODE,
  ApiError.JSON_PROPERTY_REQUEST_ID,
  ApiError.JSON_PROPERTY_DETAILS,
  ApiError.JSON_PROPERTY_RETRY_AFTER_SECONDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ApiError {
  /**
   * Fixed marker of an error response.
   */
  public enum StatusEnum {
    ERROR(String.valueOf("ERROR")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_ERROR = "error";
  @javax.annotation.Nonnull
  private String error;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  @javax.annotation.Nonnull
  private String errorCode;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_STATUS_CODE = "statusCode";
  @javax.annotation.Nonnull
  private Integer statusCode;

  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  @javax.annotation.Nonnull
  private String requestId;

  public static final String JSON_PROPERTY_DETAILS = "details";
  @javax.annotation.Nullable
  private List<ApiErrorDetailsInner> details = new ArrayList<>();

  public static final String JSON_PROPERTY_RETRY_AFTER_SECONDS = "retryAfterSeconds";
  @javax.annotation.Nullable
  private Integer retryAfterSeconds;

  public ApiError() { 
  }

  public ApiError status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Fixed marker of an error response.
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public ApiError error(@javax.annotation.Nonnull String error) {
    this.error = error;
    return this;
  }

  /**
   * Name of the corresponding HTTP status.
   * @return error
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setError(@javax.annotation.Nonnull String error) {
    this.error = error;
  }


  public ApiError errorCode(@javax.annotation.Nonnull String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Stable machine-readable error code, when available.
   * @return errorCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ERROR_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrorCode(@javax.annotation.Nonnull String errorCode) {
    this.errorCode = errorCode;
  }


  public ApiError message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Human-readable error message.
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }


  public ApiError statusCode(@javax.annotation.Nonnull Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * HTTP status code.
   * @return statusCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getStatusCode() {
    return statusCode;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusCode(@javax.annotation.Nonnull Integer statusCode) {
    this.statusCode = statusCode;
  }


  public ApiError requestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Unique request correlation ID (cuid). Include it when contacting support.
   * @return requestId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestId(@javax.annotation.Nonnull String requestId) {
    this.requestId = requestId;
  }


  public ApiError details(@javax.annotation.Nullable List<ApiErrorDetailsInner> details) {
    this.details = details;
    return this;
  }

  public ApiError addDetailsItem(ApiErrorDetailsInner detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

  /**
   * Field-level validation errors, when applicable.
   * @return details
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ApiErrorDetailsInner> getDetails() {
    return details;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetails(@javax.annotation.Nullable List<ApiErrorDetailsInner> details) {
    this.details = details;
  }


  public ApiError retryAfterSeconds(@javax.annotation.Nullable Integer retryAfterSeconds) {
    this.retryAfterSeconds = retryAfterSeconds;
    return this;
  }

  /**
   * Seconds to wait before retrying. Present only on 429 responses.
   * @return retryAfterSeconds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRY_AFTER_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRetryAfterSeconds() {
    return retryAfterSeconds;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRY_AFTER_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetryAfterSeconds(@javax.annotation.Nullable Integer retryAfterSeconds) {
    this.retryAfterSeconds = retryAfterSeconds;
  }


  /**
   * Return true if this ApiError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiError apiError = (ApiError) o;
    return Objects.equals(this.status, apiError.status) &&
        Objects.equals(this.error, apiError.error) &&
        Objects.equals(this.errorCode, apiError.errorCode) &&
        Objects.equals(this.message, apiError.message) &&
        Objects.equals(this.statusCode, apiError.statusCode) &&
        Objects.equals(this.requestId, apiError.requestId) &&
        Objects.equals(this.details, apiError.details) &&
        Objects.equals(this.retryAfterSeconds, apiError.retryAfterSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, error, errorCode, message, statusCode, requestId, details, retryAfterSeconds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiError {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    retryAfterSeconds: ").append(toIndentedString(retryAfterSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getError()))));
    }

    // add `errorCode` to the URL query string
    if (getErrorCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorCode()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `statusCode` to the URL query string
    if (getStatusCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatusCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusCode()))));
    }

    // add `requestId` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequestId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    // add `details` to the URL query string
    if (getDetails() != null) {
      for (int i = 0; i < getDetails().size(); i++) {
        if (getDetails().get(i) != null) {
          joiner.add(getDetails().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdetails%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `retryAfterSeconds` to the URL query string
    if (getRetryAfterSeconds() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretryAfterSeconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetryAfterSeconds()))));
    }

    return joiner.toString();
  }
}

