/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * CallbackDetail
 */
@JsonPropertyOrder({
  CallbackDetail.JSON_PROPERTY_ID,
  CallbackDetail.JSON_PROPERTY_URL,
  CallbackDetail.JSON_PROPERTY_STATUS,
  CallbackDetail.JSON_PROPERTY_TRANSACTION_ID,
  CallbackDetail.JSON_PROPERTY_CREATED_AT,
  CallbackDetail.JSON_PROPERTY_BODY,
  CallbackDetail.JSON_PROPERTY_RESPONSE_BODY,
  CallbackDetail.JSON_PROPERTY_RESPONSE_HEADERS,
  CallbackDetail.JSON_PROPERTY_RESPONSE_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class CallbackDetail {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private BigDecimal status;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  @javax.annotation.Nullable
  private String transactionId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_BODY = "body";
  @javax.annotation.Nullable
  private Object body;

  public static final String JSON_PROPERTY_RESPONSE_BODY = "responseBody";
  @javax.annotation.Nullable
  private String responseBody;

  public static final String JSON_PROPERTY_RESPONSE_HEADERS = "responseHeaders";
  @javax.annotation.Nullable
  private Object responseHeaders;

  public static final String JSON_PROPERTY_RESPONSE_TIME = "responseTime";
  @javax.annotation.Nullable
  private BigDecimal responseTime;

  public CallbackDetail() { 
  }

  public CallbackDetail id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique callback ID
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public CallbackDetail url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Webhook URL that received the callback
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public CallbackDetail status(@javax.annotation.Nullable BigDecimal status) {
    this.status = status;
    return this;
  }

  /**
   * HTTP response status code
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable BigDecimal status) {
    this.status = status;
  }


  public CallbackDetail transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Related transaction ID
   * @return transactionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public CallbackDetail createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Date and time when the callback log was created
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CallbackDetail body(@javax.annotation.Nullable Object body) {
    this.body = body;
    return this;
  }

  /**
   * Request body sent (parsed JSON). When the content is not valid JSON, it comes as &#x60;{ \&quot;raw\&quot;: \&quot;&lt;text&gt;\&quot; }&#x60;.
   * @return body
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@javax.annotation.Nullable Object body) {
    this.body = body;
  }


  public CallbackDetail responseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
    return this;
  }

  /**
   * Response body received (string)
   * @return responseBody
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getResponseBody() {
    return responseBody;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
  }


  public CallbackDetail responseHeaders(@javax.annotation.Nullable Object responseHeaders) {
    this.responseHeaders = responseHeaders;
    return this;
  }

  /**
   * Response headers (parsed JSON). When the content is not valid JSON, it comes as &#x60;{ \&quot;raw\&quot;: \&quot;&lt;text&gt;\&quot; }&#x60;.
   * @return responseHeaders
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getResponseHeaders() {
    return responseHeaders;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseHeaders(@javax.annotation.Nullable Object responseHeaders) {
    this.responseHeaders = responseHeaders;
  }


  public CallbackDetail responseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = responseTime;
    return this;
  }

  /**
   * Webhook round-trip time in milliseconds
   * @return responseTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getResponseTime() {
    return responseTime;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = responseTime;
  }


  /**
   * Return true if this CallbackDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallbackDetail callbackDetail = (CallbackDetail) o;
    return Objects.equals(this.id, callbackDetail.id) &&
        Objects.equals(this.url, callbackDetail.url) &&
        Objects.equals(this.status, callbackDetail.status) &&
        Objects.equals(this.transactionId, callbackDetail.transactionId) &&
        Objects.equals(this.createdAt, callbackDetail.createdAt) &&
        Objects.equals(this.body, callbackDetail.body) &&
        Objects.equals(this.responseBody, callbackDetail.responseBody) &&
        Objects.equals(this.responseHeaders, callbackDetail.responseHeaders) &&
        Objects.equals(this.responseTime, callbackDetail.responseTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, status, transactionId, createdAt, body, responseBody, responseHeaders, responseTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallbackDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("    responseHeaders: ").append(toIndentedString(responseHeaders)).append("\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `transactionId` to the URL query string
    if (getTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionId()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `responseBody` to the URL query string
    if (getResponseBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresponseBody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseBody()))));
    }

    // add `responseHeaders` to the URL query string
    if (getResponseHeaders() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresponseHeaders%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseHeaders()))));
    }

    // add `responseTime` to the URL query string
    if (getResponseTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresponseTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseTime()))));
    }

    return joiner.toString();
  }
}

