/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import br.com.payzu.pix.model.WebhookEventType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * EnqueuedCallbackItem
 */
@JsonPropertyOrder({
  EnqueuedCallbackItem.JSON_PROPERTY_TRANSACTION_ID,
  EnqueuedCallbackItem.JSON_PROPERTY_WEBHOOK_ID,
  EnqueuedCallbackItem.JSON_PROPERTY_EVENT_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class EnqueuedCallbackItem {
  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  @javax.annotation.Nullable
  private String transactionId;

  public static final String JSON_PROPERTY_WEBHOOK_ID = "webhookId";
  @javax.annotation.Nullable
  private String webhookId;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @javax.annotation.Nullable
  private WebhookEventType eventType;

  public EnqueuedCallbackItem() { 
  }

  public EnqueuedCallbackItem transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Transaction whose callback was queued.
   * @return transactionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public EnqueuedCallbackItem webhookId(@javax.annotation.Nullable String webhookId) {
    this.webhookId = webhookId;
    return this;
  }

  /**
   * Webhook that receives the delivery.
   * @return webhookId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWebhookId() {
    return webhookId;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookId(@javax.annotation.Nullable String webhookId) {
    this.webhookId = webhookId;
  }


  public EnqueuedCallbackItem eventType(@javax.annotation.Nullable WebhookEventType eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Event that triggered the callback, when the log records it.
   * @return eventType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebhookEventType getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@javax.annotation.Nullable WebhookEventType eventType) {
    this.eventType = eventType;
  }


  /**
   * Return true if this EnqueuedCallbackItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnqueuedCallbackItem enqueuedCallbackItem = (EnqueuedCallbackItem) o;
    return Objects.equals(this.transactionId, enqueuedCallbackItem.transactionId) &&
        Objects.equals(this.webhookId, enqueuedCallbackItem.webhookId) &&
        Objects.equals(this.eventType, enqueuedCallbackItem.eventType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, webhookId, eventType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnqueuedCallbackItem {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    webhookId: ").append(toIndentedString(webhookId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transactionId` to the URL query string
    if (getTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionId()))));
    }

    // add `webhookId` to the URL query string
    if (getWebhookId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhookId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhookId()))));
    }

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    return joiner.toString();
  }
}

