/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v2`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import br.com.payzu.pix.model.EnqueuedCallbackEnqueued;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * EnqueuedCallback
 */
@JsonPropertyOrder({
  EnqueuedCallback.JSON_PROPERTY_ENQUEUED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class EnqueuedCallback {
  public static final String JSON_PROPERTY_ENQUEUED = "enqueued";
  @javax.annotation.Nullable
  private EnqueuedCallbackEnqueued enqueued;

  public EnqueuedCallback() { 
  }

  public EnqueuedCallback enqueued(@javax.annotation.Nullable EnqueuedCallbackEnqueued enqueued) {
    this.enqueued = enqueued;
    return this;
  }

  /**
   * Get enqueued
   * @return enqueued
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENQUEUED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EnqueuedCallbackEnqueued getEnqueued() {
    return enqueued;
  }


  @JsonProperty(value = JSON_PROPERTY_ENQUEUED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnqueued(@javax.annotation.Nullable EnqueuedCallbackEnqueued enqueued) {
    this.enqueued = enqueued;
  }


  /**
   * Return true if this EnqueuedCallback object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnqueuedCallback enqueuedCallback = (EnqueuedCallback) o;
    return Objects.equals(this.enqueued, enqueuedCallback.enqueued);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enqueued);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnqueuedCallback {\n");
    sb.append("    enqueued: ").append(toIndentedString(enqueued)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enqueued` to the URL query string
    if (getEnqueued() != null) {
      joiner.add(getEnqueued().toUrlQueryString(prefix + "enqueued" + suffix));
    }

    return joiner.toString();
  }
}

