/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * GetUserTransactionById200ResponseAllOfCallbackLogInner
 */
@JsonPropertyOrder({
  GetUserTransactionById200ResponseAllOfCallbackLogInner.JSON_PROPERTY_ID,
  GetUserTransactionById200ResponseAllOfCallbackLogInner.JSON_PROPERTY_URL,
  GetUserTransactionById200ResponseAllOfCallbackLogInner.JSON_PROPERTY_STATUS,
  GetUserTransactionById200ResponseAllOfCallbackLogInner.JSON_PROPERTY_RESPONSE_TIME,
  GetUserTransactionById200ResponseAllOfCallbackLogInner.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class GetUserTransactionById200ResponseAllOfCallbackLogInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private Integer status;

  public static final String JSON_PROPERTY_RESPONSE_TIME = "responseTime";
  @javax.annotation.Nullable
  private BigDecimal responseTime;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public GetUserTransactionById200ResponseAllOfCallbackLogInner() { 
  }

  public GetUserTransactionById200ResponseAllOfCallbackLogInner id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Identifier of the delivery record; there is one record per callback attempt of the transaction.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public GetUserTransactionById200ResponseAllOfCallbackLogInner url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Address that received the callback: the callbackUrl of the transaction or the URL of the registered webhook.
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public GetUserTransactionById200ResponseAllOfCallbackLogInner status(@javax.annotation.Nullable Integer status) {
    this.status = status;
    return this;
  }

  /**
   * HTTP status code returned by the receiver
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable Integer status) {
    this.status = status;
  }


  public GetUserTransactionById200ResponseAllOfCallbackLogInner responseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = responseTime;
    return this;
  }

  /**
   * Round-trip time in ms
   * @return responseTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getResponseTime() {
    return responseTime;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = responseTime;
  }


  public GetUserTransactionById200ResponseAllOfCallbackLogInner createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Date and time the callback delivery attempt was recorded.
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this get_user_transaction_by_id_200_response_allOf_CallbackLog_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUserTransactionById200ResponseAllOfCallbackLogInner getUserTransactionById200ResponseAllOfCallbackLogInner = (GetUserTransactionById200ResponseAllOfCallbackLogInner) o;
    return Objects.equals(this.id, getUserTransactionById200ResponseAllOfCallbackLogInner.id) &&
        Objects.equals(this.url, getUserTransactionById200ResponseAllOfCallbackLogInner.url) &&
        Objects.equals(this.status, getUserTransactionById200ResponseAllOfCallbackLogInner.status) &&
        Objects.equals(this.responseTime, getUserTransactionById200ResponseAllOfCallbackLogInner.responseTime) &&
        Objects.equals(this.createdAt, getUserTransactionById200ResponseAllOfCallbackLogInner.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, status, responseTime, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserTransactionById200ResponseAllOfCallbackLogInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `responseTime` to the URL query string
    if (getResponseTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresponseTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseTime()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

