/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go/v3`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import br.com.payzu.pix.model.InfractionDetail;
import br.com.payzu.pix.model.InfractionListResponsePagination;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * InfractionListResponse
 */
@JsonPropertyOrder({
  InfractionListResponse.JSON_PROPERTY_INFRACTIONS,
  InfractionListResponse.JSON_PROPERTY_PAGINATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class InfractionListResponse {
  public static final String JSON_PROPERTY_INFRACTIONS = "infractions";
  @javax.annotation.Nullable
  private List<InfractionDetail> infractions = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private InfractionListResponsePagination pagination;

  public InfractionListResponse() { 
  }

  public InfractionListResponse infractions(@javax.annotation.Nullable List<InfractionDetail> infractions) {
    this.infractions = infractions;
    return this;
  }

  public InfractionListResponse addInfractionsItem(InfractionDetail infractionsItem) {
    if (this.infractions == null) {
      this.infractions = new ArrayList<>();
    }
    this.infractions.add(infractionsItem);
    return this;
  }

  /**
   * Infractions of the requested page, each in the same format as the detail.
   * @return infractions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INFRACTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<InfractionDetail> getInfractions() {
    return infractions;
  }


  @JsonProperty(value = JSON_PROPERTY_INFRACTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInfractions(@javax.annotation.Nullable List<InfractionDetail> infractions) {
    this.infractions = infractions;
  }


  public InfractionListResponse pagination(@javax.annotation.Nullable InfractionListResponsePagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public InfractionListResponsePagination getPagination() {
    return pagination;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable InfractionListResponsePagination pagination) {
    this.pagination = pagination;
  }


  /**
   * Return true if this InfractionListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfractionListResponse infractionListResponse = (InfractionListResponse) o;
    return Objects.equals(this.infractions, infractionListResponse.infractions) &&
        Objects.equals(this.pagination, infractionListResponse.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(infractions, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfractionListResponse {\n");
    sb.append("    infractions: ").append(toIndentedString(infractions)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `infractions` to the URL query string
    if (getInfractions() != null) {
      for (int i = 0; i < getInfractions().size(); i++) {
        if (getInfractions().get(i) != null) {
          joiner.add(getInfractions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sinfractions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `pagination` to the URL query string
    if (getPagination() != null) {
      joiner.add(getPagination().toUrlQueryString(prefix + "pagination" + suffix));
    }

    return joiner.toString();
  }
}

