/*
 * PayZu Pix API
 * REST API for Pix operations on the PayZu platform, deposits, withdrawals, internal transfers, infractions, reports, and callback inspection. All amounts are in BRL (reais) unless explicitly noted. Authentication uses a Bearer token issued during onboarding.  ## SDKs oficiais  - Node.js: `npm install payzu-pix` - Python: `pip install payzu-pix` - PHP: `composer require payzu/pix` - Ruby: `gem install payzu-pix` - Java: `br.com.payzu:payzu-pix` (Maven Central) - Go: `go get github.com/PayZuAI/payzu-sdks/go`  Repo: https://github.com/PayZuAI/payzu-sdks 
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.payzu.pix.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import br.com.payzu.pix.ApiClient;
/**
 * Decoded information from a Pix QR Code.
 */
@JsonPropertyOrder({
  QRCodeReadResponse.JSON_PROPERTY_QR_CODE_TYPE,
  QRCodeReadResponse.JSON_PROPERTY_NAME,
  QRCodeReadResponse.JSON_PROPERTY_DOCUMENT,
  QRCodeReadResponse.JSON_PROPERTY_AMOUNT,
  QRCodeReadResponse.JSON_PROPERTY_ORIGINAL_AMOUNT,
  QRCodeReadResponse.JSON_PROPERTY_TXID,
  QRCodeReadResponse.JSON_PROPERTY_ADDITIONAL_INFO,
  QRCodeReadResponse.JSON_PROPERTY_EXPIRES_IN,
  QRCodeReadResponse.JSON_PROPERTY_CREATED_AT,
  QRCodeReadResponse.JSON_PROPERTY_AMOUNT_EDITABLE,
  QRCodeReadResponse.JSON_PROPERTY_DUE_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class QRCodeReadResponse {
  /**
   * Type of QR Code.
   */
  public enum QrCodeTypeEnum {
    STATIC(String.valueOf("STATIC")),
    
    DYNAMIC(String.valueOf("DYNAMIC")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    QrCodeTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static QrCodeTypeEnum fromValue(String value) {
      for (QrCodeTypeEnum b : QrCodeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_QR_CODE_TYPE = "qrCodeType";
  @javax.annotation.Nullable
  private QrCodeTypeEnum qrCodeType;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DOCUMENT = "document";
  private JsonNullable<String> document = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private JsonNullable<BigDecimal> amount = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_ORIGINAL_AMOUNT = "originalAmount";
  private JsonNullable<BigDecimal> originalAmount = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_TXID = "txid";
  private JsonNullable<String> txid = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additionalInfo";
  private JsonNullable<String> additionalInfo = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXPIRES_IN = "expiresIn";
  private JsonNullable<BigDecimal> expiresIn = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private JsonNullable<OffsetDateTime> createdAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_AMOUNT_EDITABLE = "amountEditable";
  private JsonNullable<Boolean> amountEditable = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_DUE_DATE = "dueDate";
  private JsonNullable<String> dueDate = JsonNullable.<String>undefined();

  public QRCodeReadResponse() { 
  }

  public QRCodeReadResponse qrCodeType(@javax.annotation.Nullable QrCodeTypeEnum qrCodeType) {
    this.qrCodeType = qrCodeType;
    return this;
  }

  /**
   * Type of QR Code.
   * @return qrCodeType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QR_CODE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public QrCodeTypeEnum getQrCodeType() {
    return qrCodeType;
  }


  @JsonProperty(value = JSON_PROPERTY_QR_CODE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCodeType(@javax.annotation.Nullable QrCodeTypeEnum qrCodeType) {
    this.qrCodeType = qrCodeType;
  }


  public QRCodeReadResponse name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Name of the payment receiver.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public QRCodeReadResponse document(@javax.annotation.Nullable String document) {
    this.document = JsonNullable.<String>of(document);
    return this;
  }

  /**
   * CPF or CNPJ of the receiver.
   * @return document
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDocument() {
        return document.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DOCUMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDocument_JsonNullable() {
    return document;
  }
  
  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  public void setDocument_JsonNullable(JsonNullable<String> document) {
    this.document = document;
  }

  public void setDocument(@javax.annotation.Nullable String document) {
    this.document = JsonNullable.<String>of(document);
  }


  public QRCodeReadResponse amount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = JsonNullable.<BigDecimal>of(amount);
    return this;
  }

  /**
   * Amount to be paid (may differ from originalAmount for dynamic QR Codes).
   * @return amount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getAmount() {
        return amount.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getAmount_JsonNullable() {
    return amount;
  }
  
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  public void setAmount_JsonNullable(JsonNullable<BigDecimal> amount) {
    this.amount = amount;
  }

  public void setAmount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = JsonNullable.<BigDecimal>of(amount);
  }


  public QRCodeReadResponse originalAmount(@javax.annotation.Nullable BigDecimal originalAmount) {
    this.originalAmount = JsonNullable.<BigDecimal>of(originalAmount);
    return this;
  }

  /**
   * Original amount embedded in the QR Code.
   * @return originalAmount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getOriginalAmount() {
        return originalAmount.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getOriginalAmount_JsonNullable() {
    return originalAmount;
  }
  
  @JsonProperty(JSON_PROPERTY_ORIGINAL_AMOUNT)
  public void setOriginalAmount_JsonNullable(JsonNullable<BigDecimal> originalAmount) {
    this.originalAmount = originalAmount;
  }

  public void setOriginalAmount(@javax.annotation.Nullable BigDecimal originalAmount) {
    this.originalAmount = JsonNullable.<BigDecimal>of(originalAmount);
  }


  public QRCodeReadResponse txid(@javax.annotation.Nullable String txid) {
    this.txid = JsonNullable.<String>of(txid);
    return this;
  }

  /**
   * Transaction identifier.
   * @return txid
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTxid() {
        return txid.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TXID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTxid_JsonNullable() {
    return txid;
  }
  
  @JsonProperty(JSON_PROPERTY_TXID)
  public void setTxid_JsonNullable(JsonNullable<String> txid) {
    this.txid = txid;
  }

  public void setTxid(@javax.annotation.Nullable String txid) {
    this.txid = JsonNullable.<String>of(txid);
  }


  public QRCodeReadResponse additionalInfo(@javax.annotation.Nullable String additionalInfo) {
    this.additionalInfo = JsonNullable.<String>of(additionalInfo);
    return this;
  }

  /**
   * Additional information or description.
   * @return additionalInfo
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAdditionalInfo() {
        return additionalInfo.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAdditionalInfo_JsonNullable() {
    return additionalInfo;
  }
  
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  public void setAdditionalInfo_JsonNullable(JsonNullable<String> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public void setAdditionalInfo(@javax.annotation.Nullable String additionalInfo) {
    this.additionalInfo = JsonNullable.<String>of(additionalInfo);
  }


  public QRCodeReadResponse expiresIn(@javax.annotation.Nullable BigDecimal expiresIn) {
    this.expiresIn = JsonNullable.<BigDecimal>of(expiresIn);
    return this;
  }

  /**
   * Seconds until QR Code expires (0 for static QR Codes).
   * @return expiresIn
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getExpiresIn() {
        return expiresIn.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getExpiresIn_JsonNullable() {
    return expiresIn;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  public void setExpiresIn_JsonNullable(JsonNullable<BigDecimal> expiresIn) {
    this.expiresIn = expiresIn;
  }

  public void setExpiresIn(@javax.annotation.Nullable BigDecimal expiresIn) {
    this.expiresIn = JsonNullable.<BigDecimal>of(expiresIn);
  }


  public QRCodeReadResponse createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = JsonNullable.<OffsetDateTime>of(createdAt);
    return this;
  }

  /**
   * Creation date of the QR Code (for dynamic QR Codes).
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getCreatedAt() {
        return createdAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCreatedAt_JsonNullable() {
    return createdAt;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  public void setCreatedAt_JsonNullable(JsonNullable<OffsetDateTime> createdAt) {
    this.createdAt = createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = JsonNullable.<OffsetDateTime>of(createdAt);
  }


  public QRCodeReadResponse amountEditable(@javax.annotation.Nullable Boolean amountEditable) {
    this.amountEditable = JsonNullable.<Boolean>of(amountEditable);
    return this;
  }

  /**
   * Whether the payer can change the amount.
   * @return amountEditable
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Boolean getAmountEditable() {
        return amountEditable.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AMOUNT_EDITABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAmountEditable_JsonNullable() {
    return amountEditable;
  }
  
  @JsonProperty(JSON_PROPERTY_AMOUNT_EDITABLE)
  public void setAmountEditable_JsonNullable(JsonNullable<Boolean> amountEditable) {
    this.amountEditable = amountEditable;
  }

  public void setAmountEditable(@javax.annotation.Nullable Boolean amountEditable) {
    this.amountEditable = JsonNullable.<Boolean>of(amountEditable);
  }


  public QRCodeReadResponse dueDate(@javax.annotation.Nullable String dueDate) {
    this.dueDate = JsonNullable.<String>of(dueDate);
    return this;
  }

  /**
   * Due date of the charge, when the QR Code has one.
   * @return dueDate
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDueDate() {
        return dueDate.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DUE_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDueDate_JsonNullable() {
    return dueDate;
  }
  
  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  public void setDueDate_JsonNullable(JsonNullable<String> dueDate) {
    this.dueDate = dueDate;
  }

  public void setDueDate(@javax.annotation.Nullable String dueDate) {
    this.dueDate = JsonNullable.<String>of(dueDate);
  }


  /**
   * Return true if this QRCodeReadResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QRCodeReadResponse qrCodeReadResponse = (QRCodeReadResponse) o;
    return Objects.equals(this.qrCodeType, qrCodeReadResponse.qrCodeType) &&
        equalsNullable(this.name, qrCodeReadResponse.name) &&
        equalsNullable(this.document, qrCodeReadResponse.document) &&
        equalsNullable(this.amount, qrCodeReadResponse.amount) &&
        equalsNullable(this.originalAmount, qrCodeReadResponse.originalAmount) &&
        equalsNullable(this.txid, qrCodeReadResponse.txid) &&
        equalsNullable(this.additionalInfo, qrCodeReadResponse.additionalInfo) &&
        equalsNullable(this.expiresIn, qrCodeReadResponse.expiresIn) &&
        equalsNullable(this.createdAt, qrCodeReadResponse.createdAt) &&
        equalsNullable(this.amountEditable, qrCodeReadResponse.amountEditable) &&
        equalsNullable(this.dueDate, qrCodeReadResponse.dueDate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(qrCodeType, hashCodeNullable(name), hashCodeNullable(document), hashCodeNullable(amount), hashCodeNullable(originalAmount), hashCodeNullable(txid), hashCodeNullable(additionalInfo), hashCodeNullable(expiresIn), hashCodeNullable(createdAt), hashCodeNullable(amountEditable), hashCodeNullable(dueDate));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QRCodeReadResponse {\n");
    sb.append("    qrCodeType: ").append(toIndentedString(qrCodeType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    originalAmount: ").append(toIndentedString(originalAmount)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    amountEditable: ").append(toIndentedString(amountEditable)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `qrCodeType` to the URL query string
    if (getQrCodeType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sqrCodeType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQrCodeType()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `document` to the URL query string
    if (getDocument() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdocument%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDocument()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `originalAmount` to the URL query string
    if (getOriginalAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soriginalAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOriginalAmount()))));
    }

    // add `txid` to the URL query string
    if (getTxid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stxid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTxid()))));
    }

    // add `additionalInfo` to the URL query string
    if (getAdditionalInfo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadditionalInfo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdditionalInfo()))));
    }

    // add `expiresIn` to the URL query string
    if (getExpiresIn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiresIn%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresIn()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `amountEditable` to the URL query string
    if (getAmountEditable() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samountEditable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmountEditable()))));
    }

    // add `dueDate` to the URL query string
    if (getDueDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdueDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDueDate()))));
    }

    return joiner.toString();
  }
}

